### ISSUE TITLE
Need best practice to create more then one instance with storage and network configuration and apply custom script after instance creation.

### ISSUE THREAD

**Issue by gupraj** [terraform-providers/terraform-provider-opc#101]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.10.4.

### Affected Resource(s)
Please list the resources as a list, for example:
- opc_instance
- opc_storage_volume
- Terraform
- custom script

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```
Not Available.

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
Need best practice to create more then one instance with storage and network configuration and apply custom script after instance creation.
How to write or any test case available for dynamic script to create OPC instance,network,storage and run custom script.

### Actual Behavior
N/A

### Steps to Reproduce
 `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by scross01** [comment]
The below example creates multiple instances with bootable storage using the resource `count`  attribute.

- the variable `instance_count` sets the number of instances to create
- the resource `count.index` is used in the resource name to give each instance and storage volume a unique name
- the `element()` interpolation function is used in the instance `storage` block to to reference the storage volume resource with the same count index.

There are multiple approaches to declaring the instance initialization scripts. Depending on your requirements and base OS you can initialize instances using opc-init, cloud-init, or Terraform provisioners. The example below shows an `opc-init` pre-boot script passed in to the instance userdata. Take a look at the article [Automating Instance Initialization with Terraform on Oracle's Compute Cloud](https://medium.com/oracledevs/automating-oracle-compute-cloud-instance-initialization-with-terraform-6e66968fe30a) for other examples.

```hcl
variable instance_count { default = 2 }

data "template_file" "opc-init-preboot" {
  template = <<JSON
{
  "userdata": {
    "pre-bootstrap": {
      "script": [
        "echo 'This instance was provisioned by Terraform.' >> /etc/motd"
      ]
    }
  }
}
JSON
}

resource "opc_compute_storage_volume" "boot-volumes" {
  count            = "${var.instance_count}"
  size             = "12"
  name             = "${format("bootvolume-%03d", count.index + 1)}"
  bootable         = true
  image_list       = "/oracle/public/OL_7.2_UEKR4_x86_64"
  image_list_entry = 1
}

resource "opc_compute_instance" "instances" {
  count = "${var.instance_count}"
  name  = "${format("instance-%03d", count.index + 1)}"
  shape = "oc3"
  instance_attributes = "${data.template_file.opc-init-preboot.rendered}"

  storage {
    index  = 1
    volume = "${element(opc_compute_storage_volume.boot-volumes.*.name,count.index)}"
  }

  boot_order = [1]
}
```

**Comment by gupraj** [comment]
Thanks for update, I have some more question on this,but unfortunately busy in something else. raised new issue for the same. I will get back to you on this.

Once again thank  you so much.

**Comment by scross01** [comment]
@gupraj do you have any more questions on this, or can the issue be closed?
