### ISSUE TITLE
terraform crashed, stuck in network configuration

### ISSUE THREAD

**Issue by gupraj** [terraform-providers/terraform-provider-opc#104]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.11.1
+ provider.opc v0.1.3

### Affected Resource(s)
Please list the resources as a list, for example:
- opc network 

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

Unable to provide crash.log

### Expected Behavior
What should have happened?

### Actual Behavior
Cashed, and resource not present in OPC but still show already present

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by gupraj** [comment]
@scross01 Please help.

C:\terraform prod>terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  + opc_compute_acl.APP-DATA-ACL
      id:              <computed>
      enabled:         "true"
      name:            "APP-DATA-ACL"
      uri:             <computed>

  + opc_compute_acl.APP-replication-ACL
      id:              <computed>
      enabled:         "true"
      name:            "APP-replication-ACL"
      uri:             <computed>

  + opc_compute_acl.DB-DATA-ACL
      id:              <computed>
      enabled:         "true"
      name:            "DB-DATA-ACL"
      uri:             <computed>

  + opc_compute_acl.DB-replication-ACL
      id:              <computed>
      enabled:         "true"
      name:            "DB-replication-ACL"
      uri:             <computed>

  + opc_compute_acl.FORTIGATE-ACL
      id:              <computed>
      enabled:         "true"
      name:            "FORTIGATE-ACL"
      uri:             <computed>

  + opc_compute_vnic_set.APP-DATA-VNICSET
      id:              <computed>
      applied_acls.#:  "1"
      applied_acls.0:  "APP-DATA-ACL"
      name:            "APP-DATA-VNICSET"
      virtual_nics.#:  "23"
      virtual_nics.0:  "ADMINDRMGTANC01_eth1"
      virtual_nics.1:  "ADDRMGTAPP01_eth1"
      virtual_nics.10: "EXCDRAPP01B_eth1"
      virtual_nics.11: "INFRDRSYSLOG_eth1"
      virtual_nics.12: "MONDRMGTSS03_eth1"
      virtual_nics.13: "OIDDRMGTAPP01A_eth1"
      virtual_nics.14: "OIDDRMGTAPP01B_eth1"
      virtual_nics.15: "OIMDRMGTAPP01_eth1"
      virtual_nics.16: "RETDRAPP01A_eth1"
      virtual_nics.17: "RETDRAPP01B_eth1"
      virtual_nics.18: "RETDRAPP02A_eth1"
      virtual_nics.19: "RETDRAPP02B_eth1"
      virtual_nics.2:  "ADSVNTST_eth1"
      virtual_nics.20: "RETDRAPP03_eth1"
      virtual_nics.21: "RETDRSS01_eth1"
      virtual_nics.22: "XSTOREDRSRV1_eth1"
      virtual_nics.3:  "AIADRAPP01A_eth1"
      virtual_nics.4:  "AIADRAPP01B_eth1"
      virtual_nics.5:  "BIADRAPP01_eth1"
      virtual_nics.6:  "CODEMGMTDR_eth1"
      virtual_nics.7:  "EBSDRAPP01A_eth1"
      virtual_nics.8:  "EBSDRAPP01B_eth1"
      virtual_nics.9:  "EXCDRAPP01A_eth1"

  + opc_compute_vnic_set.DB-DATA-VNICSET
      id:              <computed>
      applied_acls.#:  "1"
      applied_acls.0:  "DB-DATA-ACL"
      name:            "DB-DATA-VNICSET"
      virtual_nics.#:  "11"
      virtual_nics.0:  "AIADRDB01_eth1"
      virtual_nics.1:  "BIADRDB01_eth1"
      virtual_nics.10: "RETDRDB03_eth1"
      virtual_nics.2:  "BIADRDB02_eth1"
      virtual_nics.3:  "EBSDRDB01_eth1"
      virtual_nics.4:  "EXCDRDB01_eth1"
      virtual_nics.5:  "INFRDRMGT01_eth1"
      virtual_nics.6:  "OIDOIMDRMGTDB01_eth1"
      virtual_nics.7:  "RETDRDB01_eth1"
      virtual_nics.8:  "XSTOREDRDBSRV1_eth1"
      virtual_nics.9:  "RETDRDB02_eth1"


Plan: 7 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.


C:\terraform prod>terraform apply
opc_compute_acl.FORTIGATE-ACL: Creating...
  enabled: "" => "true"
  name:    "" => "FORTIGATE-ACL"
  uri:     "" => "<computed>"
opc_compute_acl.APP-replication-ACL: Creating...
  enabled: "" => "true"
  name:    "" => "APP-replication-ACL"
  uri:     "" => "<computed>"
opc_compute_acl.DB-replication-ACL: Creating...
  enabled: "" => "true"
  name:    "" => "DB-replication-ACL"
  uri:     "" => "<computed>"
opc_compute_acl.DB-DATA-ACL: Creating...
  enabled: "" => "true"
  name:    "" => "DB-DATA-ACL"
  uri:     "" => "<computed>"
opc_compute_acl.APP-DATA-ACL: Creating...
  enabled: "" => "true"
  name:    "" => "APP-DATA-ACL"
  uri:     "" => "<computed>"
opc_compute_acl.APP-DATA-ACL: Creation complete after 6s (ID: APP-DATA-ACL)
opc_compute_vnic_set.APP-DATA-VNICSET: Creating...
  applied_acls.#:  "" => "1"
  applied_acls.0:  "" => "APP-DATA-ACL"
  name:            "" => "APP-DATA-VNICSET"
  virtual_nics.#:  "" => "23"
  virtual_nics.0:  "" => "ADMINDRMGTANC01_eth1"
  virtual_nics.1:  "" => "ADDRMGTAPP01_eth1"
  virtual_nics.10: "" => "EXCDRAPP01B_eth1"
  virtual_nics.11: "" => "INFRDRSYSLOG_eth1"
  virtual_nics.12: "" => "MONDRMGTSS03_eth1"
  virtual_nics.13: "" => "OIDDRMGTAPP01A_eth1"
  virtual_nics.14: "" => "OIDDRMGTAPP01B_eth1"
  virtual_nics.15: "" => "OIMDRMGTAPP01_eth1"
  virtual_nics.16: "" => "RETDRAPP01A_eth1"
  virtual_nics.17: "" => "RETDRAPP01B_eth1"
  virtual_nics.18: "" => "RETDRAPP02A_eth1"
  virtual_nics.19: "" => "RETDRAPP02B_eth1"
  virtual_nics.2:  "" => "ADSVNTST_eth1"
  virtual_nics.20: "" => "RETDRAPP03_eth1"
  virtual_nics.21: "" => "RETDRSS01_eth1"
  virtual_nics.22: "" => "XSTOREDRSRV1_eth1"
  virtual_nics.3:  "" => "AIADRAPP01A_eth1"
  virtual_nics.4:  "" => "AIADRAPP01B_eth1"
  virtual_nics.5:  "" => "BIADRAPP01_eth1"
  virtual_nics.6:  "" => "CODEMGMTDR_eth1"
  virtual_nics.7:  "" => "EBSDRAPP01A_eth1"
  virtual_nics.8:  "" => "EBSDRAPP01B_eth1"
  virtual_nics.9:  "" => "EXCDRAPP01A_eth1"
opc_compute_acl.APP-replication-ACL: Creation complete after 9s (ID: APP-replication-ACL)
opc_compute_vnic_set.APP-DATA-VNICSET: Creation complete after 6s (ID: APP-DATA-VNICSET)
Error applying plan:

3 error(s) occurred:

* opc_compute_acl.DB-replication-ACL: 1 error(s) occurred:

* opc_compute_acl.DB-replication-ACL: Error creating ACL: 409: {"message": "entity with name /Compute-a494031/raj.a.gupta@accenture.com/DB-replication-ACL already exists"}
* opc_compute_acl.FORTIGATE-ACL: 1 error(s) occurred:

* opc_compute_acl.FORTIGATE-ACL: Error creating ACL: 409: {"message": "entity with name /Compute-a494031/raj.a.gupta@accenture.com/FORTIGATE-ACL already exists"}
* opc_compute_acl.DB-DATA-ACL: 1 error(s) occurred:

* opc_compute_acl.DB-DATA-ACL: Error creating ACL: 409: {"message": "entity with name /Compute-a494031/raj.a.gupta@accenture.com/DB-DATA-ACL already exists"}

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

C:\terraform prod>

**Comment by gupraj** [comment]
this is just example, I have huge code for configuring my network for opc, but all get failed and crashed.

**Comment by gupraj** [comment]
@scross01 @mbfrahry  please suggest.

Below is the carsh log details-
* opc_compute_security_rule.EBSDRAPP01B-INGRESS: 1 error(s) occurred:

* opc_compute_security_rule.EBSDRAPP01B-INGRESS: Error creating Security Rule: 409: {"message": "entity with name /Compute-a494031/raj.a.gupta@accenture.com/EBSDRAPP01B-INGRESS already exists"}
* opc_compute_security_rule.BIADRDB02-INGRESS: 1 error(s) occurred:

* opc_compute_security_rule.BIADRDB02-INGRESS: unexpected EOF
* opc_compute_ip_address_prefix_set.BIADRDB02-PREFIX: 1 error(s) occurred:

* opc_compute_ip_address_prefix_set.BIADRDB02-PREFIX: unexpected EOF
* opc_compute_vnic_set.FORTIGATE-VNICSET: Resource 'opc_compute_acl.FORTIGATE-ACL' not found for variable 'opc_compute_acl.FORTIGATE-ACL.name'
* opc_compute_acl.DB-replication-ACL: 1 error(s) occurred:

* opc_compute_acl.DB-replication-ACL: Error creating ACL: 409: {"message": "entity with name /Compute-a494031/raj.a.gupta@accenture.com/DB-replication-ACL already exists"}
* opc_compute_security_rule.DB-DATA-INT-EGRESS: 1 error(s) occurred:

* opc_compute_security_rule.DB-DATA-INT-EGRESS: unexpected EOF
* opc_compute_security_rule.RETDRDB01-INGRESS: 1 error(s) occurred:

* opc_compute_security_rule.RETDRDB01-INGRESS: unexpected EOF
* opc_compute_ip_address_prefix_set.RETDRDB02-PREFIX: 1 error(s) occurred:

* opc_compute_ip_address_prefix_set.RETDRDB02-PREFIX: unexpected EOF
* opc_compute_ip_address_prefix_set.EXCDRDB01-PREFIX: 1 error(s) occurred:

* opc_compute_ip_address_prefix_set.EXCDRDB01-PREFIX: unexpected EOF
* opc_compute_security_rule.MONDRMGTSS03-INGRESS: 1 error(s) occurred:

* opc_compute_security_rule.MONDRMGTSS03-INGRESS: unexpected EOF
* opc_compute_ip_address_prefix_set.RETDRAPP02B-PREFIX: 1 error(s) occurred:

* opc_compute_ip_address_prefix_set.RETDRAPP02B-PREFIX: unexpected EOF
* opc_compute_security_rule.APP-DATA-EGRESS: 1 error(s) occurred:

* opc_compute_security_rule.APP-DATA-EGRESS: unexpected EOF
* opc_compute_vnic_set.APP-DATA-VNICSET: Resource 'opc_compute_acl.APP-DATA-ACL' not found for variable 'opc_compute_acl.APP-DATA-ACL.name'
* opc_compute_ip_address_prefix_set.ADSVNTST-PREFIX: 1 error(s) occurred:

* opc_compute_ip_address_prefix_set.ADSVNTST-PREFIX: Error creating IP Address Prefix Set: 409: {"message": "entity with name /Compute-a494031/raj.a.gupta@accenture.com/ADSVNTST-PREFIX already exists"}
* opc_compute_security_rule.OIMDRMGTAPP01-INGRESS: 1 error(s) occurred:

* opc_compute_security_rule.OIMDRMGTAPP01-INGRESS: unexpected EOF
* opc_compute_ip_address_prefix_set.RETDRAPP02A-PREFIX: connection is shut down
* opc_compute_security_rule.ADDRMGTAPP01-INGRESS: connection is shut down
* opc_compute_ip_address_prefix_set.INFRDRMGT01-PREFIX: connection is shut down
* opc_compute_security_rule.APP-REPLICATION-INGRESS: connection is shut down
* opc_compute_security_rule.DB-REPLICATION-EGRESS: connection is shut down
* opc_compute_security_rule.INFRDRMGT01-INGRESS: connection is shut down
* opc_compute_security_rule.XSTOREDRDBSRV1-INGRESS: connection is shut down
* opc_compute_ip_address_prefix_set.OIMDRMGTAPP01-PREFIX: connection is shut down
* opc_compute_ip_address_prefix_set.ADDRMGTAPP01-PREFIX: connection is shut down
* opc_compute_security_rule.APP-DATA-INT-INGRESS: connection is shut down
* opc_compute_security_rule.RETDRAPP02B-INGRESS: connection is shut down
* opc_compute_security_rule.EXCDRAPP01B-INGRESS: connection is shut down
* opc_compute_ip_address_prefix_set.MONDRMGTSS03-PREFIX: connection is shut down
* opc_compute_ip_address_prefix_set.INFRDRSYSLOG-PREFIX: connection is shut down
* opc_compute_security_rule.BIADRAPP01-INGRESS: connection is shut down
* opc_compute_ip_address_prefix_set.EBSDRAPP01B-PREFIX: connection is shut down
* opc_compute_security_rule.RETDRSS01-INGRESS: connection is shut down
* opc_compute_security_rule.INFRDRSYSLOG-INGRESS: connection is shut down
* opc_compute_ip_address_prefix_set.AIADRDB01-PREFIX: connection is shut down
* opc_compute_acl.APP-replication-ACL: connection is shut down
* opc_compute_ip_address_prefix_set.RETDRDB01-PREFIX: connection is shut down
* opc_compute_ip_address_prefix_set.APP-DATA-PREFIX: connection is shut down
* opc_compute_ip_address_prefix_set.ADMINDRMGTANC01-PREFIX: connection is shut down
* opc_compute_ip_address_prefix_set.OIDDRMGTAPP01A-PREFIX: connection is shut down
* opc_compute_security_rule.CODEMGMTDR-INGRESS: connection is shut down
* opc_compute_security_rule.DB-DATA-EGRESS: connection is shut down
* opc_compute_ip_address_prefix_set.EXCDRAPP01A-PREFIX: connection is shut down
* opc_compute_acl.FORTIGATE-ACL: connection is shut down
* opc_compute_security_rule.RETDRAPP01B-INGRESS: connection is shut down
* opc_compute_ip_address_prefix_set.VPN-PREFIX: connection is shut down
* opc_compute_ip_address_prefix_set.EBSDRDB01-PREFIX: connection is shut down
* opc_compute_ip_address_prefix_set.CHALHOUB-PREFIX: connection is shut down
* opc_compute_security_rule.DB-DATA-INT-INGRESS: connection is shut down
* opc_compute_security_rule.RETDRDB03-INGRESS: connection is shut down
* opc_compute_security_rule.FORTIGATE-INGRESS: connection is shut down
* opc_compute_security_protocol.ICMP: connection is shut down
* opc_compute_ip_address_prefix_set.EBSDRAPP01A-PREFIX: connection is shut down
* opc_compute_security_rule.RETDRAPP01A-INGRESS: connection is shut down
* opc_compute_ip_address_prefix_set.DB-REPLICATION-PREFIX: connection is shut down
* opc_compute_ip_address_prefix_set.AIADRAPP01A-PREFIX: connection is shut down
* opc_compute_ip_address_prefix_set.RETDRAPP01B-PREFIX: connection is shut down
* opc_compute_security_rule.APP-REPLICATION-EGRESS: connection is shut down
* opc_compute_ip_address_prefix_set.RETDRAPP03-PREFIX: connection is shut down
* opc_compute_ip_address_prefix_set.RETDRDB03-PREFIX: connection is shut down
* opc_compute_ip_address_prefix_set.CODEMGMTDR-PREFIX: connection is shut down
* opc_compute_security_rule.EXCDRAPP01A-INGRESS: connection is shut down
* opc_compute_security_rule.XSTOREDRSRV1-INGRESS: connection is shut down
* opc_compute_ip_address_prefix_set.BIADRDB01-PREFIX: connection is shut down
* opc_compute_security_rule.RETDRAPP02A-INGRESS: connection is shut down
* opc_compute_acl.APP-DATA-ACL: connection is shut down
* opc_compute_security_rule.EBSDRAPP01A-INGRESS: connection is shut down
* opc_compute_ip_address_prefix_set.XSTOREDRDBSRV1-PREFIX: connection is shut down
* opc_compute_security_rule.OIDOIMDRMGTDB01-INGRESS: connection is shut down
* opc_compute_ip_address_prefix_set.DB-DATA-PREFIX: connection is shut down
* opc_compute_security_protocol.SSH: connection is shut down
* opc_compute_ip_address_prefix_set.JUMP-PREFIX: connection is shut down
* opc_compute_vnic_set.DB-DATA-VNICSET: connection is shut down
* opc_compute_security_rule.OIDDRMGTAPP01B-INGRESS: connection is shut down
* opc_compute_security_rule.BIADRDB01-INGRESS: connection is shut down
* opc_compute_ip_address_prefix_set.RETDRSS01-PREFIX: connection is shut down
* opc_compute_security_rule.EBSDRDB01-INGRESS: connection is shut down
* opc_compute_security_rule.FORTIGATE-EGRESS: connection is shut down
* opc_compute_security_rule.AIADRDB01-INGRESS: connection is shut down
* opc_compute_security_rule.AIADRAPP01B-INGRESS: connection is shut down

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
panic: interface conversion: interface {} is nil, not string
2017-12-21T16:55:08.607+0530 [DEBUG] plugin.terraform-provider-opc_v1.0.1_x4.exe:
2017-12-21T16:55:08.607+0530 [DEBUG] plugin.terraform-provider-opc_v1.0.1_x4.exe: goroutine 810 [running]:
2017-12-21T16:55:08.607+0530 [DEBUG] plugin.terraform-provider-opc_v1.0.1_x4.exe: github.com/terraform-providers/terraform-provider-opc/opc.getStringList(0xc04207c1c0, 0xc15e81, 0x17, 0xc042468160, 0x1, 0x1)
2017-12-21T16:55:08.607+0530 [DEBUG] plugin.terraform-provider-opc_v1.0.1_x4.exe:       /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-opc/opc/helpers.go:17 +0x225
2017-12-21T16:55:08.607+0530 [DEBUG] plugin.terraform-provider-opc_v1.0.1_x4.exe: github.com/terraform-providers/terraform-provider-opc/opc.resourceOPCSecurityRuleCreate(0xc04207c1c0, 0xacc420, 0xc042486260, 0x24, 0x10d2dc0)
2017-12-21T16:55:08.607+0530 [DEBUG] plugin.terraform-provider-opc_v1.0.1_x4.exe:       /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-opc/opc/resource_security_rule.go:106 +0x4b8
2017-12-21T16:55:08.607+0530 [DEBUG] plugin.terraform-provider-opc_v1.0.1_x4.exe: github.com/terraform-providers/terraform-provider-opc/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Apply(0xc04253cc60, 0xc0423be500, 0xc04246f000, 0xacc420, 0xc042486260, 0x1, 0xc0423ca480, 0x0)
2017-12-21T16:55:08.607+0530 [DEBUG] plugin.terraform-provider-opc_v1.0.1_x4.exe:       /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-opc/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:193 +0x3bd
2017-12-21T16:55:08.607+0530 [DEBUG] plugin.terraform-provider-opc_v1.0.1_x4.exe: github.com/terraform-providers/terraform-provider-opc/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Apply(0xc04224fa40, 0xc0423be4b0, 0xc0423be500, 0xc04246f000, 0x14713f8, 0x0, 0x0)
2017-12-21T16:55:08.607+0530 [DEBUG] plugin.terraform-provider-opc_v1.0.1_x4.exe:       /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-opc/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:259 +0xab
2017-12-21T16:55:08.608+0530 [DEBUG] plugin.terraform-provider-opc_v1.0.1_x4.exe: github.com/terraform-providers/terraform-provider-opc/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Apply(0xc0423107e0, 0xc04246efa0, 0xc0423bd4b0, 0x0, 0x0)
2017-12-21T16:55:08.608+0530 [DEBUG] plugin.terraform-provider-opc_v1.0.1_x4.exe:       /opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-opc/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:488 +0x5e
2017-12-21T16:55:08.608+0530 [DEBUG] plugin.terraform-provider-opc_v1.0.1_x4.exe: reflect.Value.call(0xc042037ec0, 0xc0421f3d70, 0x13, 0xc059e0, 0x4, 0xc0422b3f20, 0x3, 0x3, 0xc0422b3ec8, 0xc0422b3ee8, ...)
2017-12-21T16:55:08.608+0530 [DEBUG] plugin.terraform-provider-opc_v1.0.1_x4.exe:       /usr/local/go/src/reflect/value.go:434 +0x90c
2017-12-21T16:55:08.608+0530 [DEBUG] plugin.terraform-provider-opc_v1.0.1_x4.exe: reflect.Value.Call(0xc042037ec0, 0xc0421f3d70, 0x13, 0xc0422b3f20, 0x3, 0x3, 0xc0422b3f30, 0x1, 0x0)
2017-12-21T16:55:08.608+0530 [DEBUG] plugin.terraform-provider-opc_v1.0.1_x4.exe:       /usr/local/go/src/reflect/value.go:302 +0xab
2017-12-21T16:55:08.608+0530 [DEBUG] plugin.terraform-provider-opc_v1.0.1_x4.exe: net/rpc.(*service).call(0xc0423aea40, 0xc0423e8d70, 0xc0424b1f38, 0xc042508500, 0xc0421fa0a0, 0xad0da0, 0xc04246efa0, 0x16, 0xad0de0, 0xc0423bd4b0, ...)
2017-12-21T16:55:08.608+0530 [DEBUG] plugin.terraform-provider-opc_v1.0.1_x4.exe:       /usr/local/go/src/net/rpc/server.go:381 +0x149
2017-12-21T16:55:08.608+0530 [DEBUG] plugin.terraform-provider-opc_v1.0.1_x4.exe: created by net/rpc.(*Server).ServeCodec
2017-12-21T16:55:08.608+0530 [DEBUG] plugin.terraform-provider-opc_v1.0.1_x4.exe:       /usr/local/go/src/net/rpc/server.go:475 +0x372
2017-12-21T16:55:08.644+0530 [DEBUG] plugin: plugin process exited: path=C:\terraform\.terraform\plugins\windows_amd64\terraform-provider-opc_v1.0.1_x4.exe

**Comment by scross01** [comment]
@gupraj the first errors imply the resources are already present, check you don't have duplicate definitions inf the tf config, and that the ACLs aren't already created in the target environment.  If they are already present then either delete the, or `import` them into the local state file.

Did the issues just start after updating to `v1.0.1` of the provider?  You could try rolling back to older version by putting the `version = 0.1.3` in the provider block.

**Comment by scross01** [comment]
also, it looks like you may be declaring all the vnics in the vnic set resource definition. My suggestion would be to *not* include the `virtual_nics` attribute the `opc_compute_vnic_set` resource, but instead make sure the `vnic_sets` is set in the instance `networking_info` block.  

Take a look at this article for more details
https://medium.com/oracledevs/working-with-oracle-cloud-infrastructure-classic-security-rules-in-terraform-part-2-ip-networks-b36c48d87330

**Comment by gupraj** [comment]
@scross01 Thanks for reply.

Issue is coming with both version.
I had created all the VM using jason and now trying to add network configuration. 
Let me check the details of above link, will keep you posted the update.


Thanks

**Comment by scross01** [comment]
@gupraj did the suggestions resolve your problem, can this issue be close?

**Comment by gupraj** [comment]
@scross01  Really sorry delay :(

Yes,it helps me. Please close this issue. I would like to appreciate you for your prompt help :) Thank you so much.

Regards.
Raj Gupta
