### ISSUE TITLE
Unnecessary Storage Volume Destruction

### ISSUE THREAD

**Issue by fribeiro1** [terraform-providers/terraform-provider-opc#106]
### Terraform Version
Terraform v0.11.1
provider.opc v1.0.1

### Affected Resource(s)
- opc_compute_storage_volume

### Terraform Configuration Files
```hcl
resource "opc_compute_storage_volume" "SampleVolume" {
  name = "SampleVolume"
  bootable = true
  image_list = "/oracle/public/OL_7.2_UEKR4_x86_64"
  size = 128
}
```

### Debug Output
https://gist.github.com/fribeiro1/3fecc38de4eba852af91ae0545e735c7

### Panic Output
N/A

### Expected Behavior
The storage volume isn't re-created because there isn't any change.

### Actual Behavior
The storage volume is re-created.

### Steps to Reproduce
1. `terraform apply`
2. `terraform apply`

### Important Factoids
None

### References
None

**Comment by scross01** [comment]
The problem appears to be this line in the logs:

```
 image_list_entry: "2" => "-1" (forces new resource)
```

Because `image_list_entry` is not explicitly set in the config it's defaulting to `-1` but then the diff is different than for the actual entry used `2` (i.e. it's picking the latest entry in the image list)

Workaround is to explicitly set `image_list_entry = 2`

Fix should ignore the compare when `image_list_entry = -1` (i.e. use default) to prevent the resource getting recreated on second apply

**Comment by melbeans** [comment]
Martin 


>   That was what thought but wanted to confirm with you as I had someone today me Feb 2018. Does that timeframe sound correct?

Thank You


Mel

**Comment by melbeans** [comment]
I can’t confirm that (as unfortunately I’m not on that team), but I’m sure a Terraform representative will.

 

From: Melvin Beans 
Sent: Tuesday, January 9, 2018 11:02 AM
To: Martin Sleeman <martin.sleeman@oracle.com>
Cc: terraform-providers/terraform-provider-opc <reply@reply.github.com>; terraform-providers/terraform-provider-opc <terraform-provider-opc@noreply.github.com>; Bruce Burns <bruce.burns@oracle.com>; Kiran Davuluri <kiran.davuluri@oracle.com>
Subject: Re: OCI Tagging Terraform

 

Martin 

 

 

  That was what thought but wanted to confirm with you as I had someone today me Feb 2018. Does that timeframe sound correct?

 

Thank You

 

 

Mel

Sent from my iPhone


On Jan 9, 2018, at 1:49 PM, Martin Sleeman <HYPERLINK "mailto:martin.sleeman@oracle.com"martin.sleeman@oracle.com> wrote:

Hi Mel,

 

Currently there is no support for tagging inside the Terraform provider.  However the request for a feature has been requested (#400 in GitHub I believe) and the team is planning on supporting Tagging soon.

 

Thx

-Martin

 

From: Mel Beans 
Sent: Tuesday, January 9, 2018 5:01 AM
To: terraform-providers/terraform-provider-opc <HYPERLINK "mailto:reply@reply.github.com"reply@reply.github.com>; terraform-providers/terraform-provider-opc <HYPERLINK "mailto:terraform-provider-opc@noreply.github.com"terraform-provider-opc@noreply.github.com>
Cc: Martin Sleeman <HYPERLINK "mailto:martin.sleeman@oracle.com"martin.sleeman@oracle.com>; Bruce Burns <HYPERLINK "mailto:bruce.burns@oracle.com"bruce.burns@oracle.com>; Kiran Davuluri <HYPERLINK "mailto:kiran.davuluri@oracle.com"kiran.davuluri@oracle.com>
Subject: OCI Tagging Terraform

 

All:

 

   Tagging a new feature of OCI & looking in doc for rerferences for it in doc but do not see it unless I missing it. Please confirm I missing it & if so point me to doc section? If not missing it let me know so I can submit ER.

 

https://docs.us-phoenix-1.oraclecloud.com/Content/API/Concepts/sdkconfig.htm

 

 

Thank You

 

mel

 

-- 
HYPERLINK "http://www.oracle.com/"<image001.gif>
Mel Beans | Master Principal Solutions Consultant
Mobile: 2052136221 | VOIP: 6505064968 

https://myoracle.webex.com/join/mel.beans

Oracle ISV/OEM

HYPERLINK "http://www.oracle.com/commitment"<image002.gif>

Oracle is committed to developing practices and products that help protect the environment

**Comment by melbeans** [comment]
Hi Mel,

 

Currently there is no support for tagging inside the Terraform provider.  However the request for a feature has been requested (#400 in GitHub I believe) and the team is planning on supporting Tagging soon.

 

Thx

-Martin

 

From: Mel Beans 
Sent: Tuesday, January 9, 2018 5:01 AM
To: terraform-providers/terraform-provider-opc <reply@reply.github.com>; terraform-providers/terraform-provider-opc <terraform-provider-opc@noreply.github.com>
Cc: Martin Sleeman <martin.sleeman@oracle.com>; Bruce Burns <bruce.burns@oracle.com>; Kiran Davuluri <kiran.davuluri@oracle.com>
Subject: OCI Tagging Terraform

 

All:

 

   Tagging a new feature of OCI & looking in doc for rerferences for it in doc but do not see it unless I missing it. Please confirm I missing it & if so point me to doc section? If not missing it let me know so I can submit ER.

 

https://docs.us-phoenix-1.oraclecloud.com/Content/API/Concepts/sdkconfig.htm

 

 

Thank You

 

mel

 

-- 
http://www.oracle.com/
Mel Beans | Master Principal Solutions Consultant
Mobile: 2052136221 | VOIP: 6505064968 

https://myoracle.webex.com/join/mel.beans

Oracle ISV/OEM

http://www.oracle.com/commitment

Oracle is committed to developing practices and products that help protect the environment

**Comment by fribeiro1** [comment]
Out of date.
