### ISSUE TITLE
Error in Orchestrated Instances Documentation

### ISSUE THREAD

**Issue by fribeiro1** [terraform-providers/terraform-provider-opc#110]
### Terraform Version
N/A

### Affected Resource(s)
- opc_compute_orchestrated_instance

### Terraform Configuration Files
N/A

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
N/A

### Actual Behavior
The object_label key mentioned in https://www.terraform.io/docs/providers/opc/r/opc_compute_orchestrated_instance.html doesn't really exist.

### Steps to Reproduce
N/A

### Important Factoids
N/A

### References
N/A

**Comment by scross01** [comment]
Well spotted 👀
