### ISSUE TITLE
Terraform-Provider-OCI Help Required 

### ISSUE THREAD

**Issue by gupraj** [terraform-providers/terraform-provider-opc#121]
Hi there,

Please mark this request as question.

### Affected Resource(s)
Please list the resources as a list, for example:
- oci_instance
- oci_storage_volume
-oci_network
Need help! How to build OCI resource (Network,Compute,Storage) for IaaS and PaaS.

Please provide share custom template to create IaaS and PaaS resources using terraform.

thanks in advance.

**Comment by gupraj** [comment]
@scross01  Please help!

https://www.terraform.io/docs/providers/opc/index.html-  available for OPC

**Comment by scross01** [comment]
There is an example of deploying Oracle Database Cloud Service on OCI using both the `oraclepaas` and `oci` providers at https://github.com/oracle/terraform-examples/tree/master/examples/oraclepaas/dbcs-instance-oci

If you have any questions on the example please open an issue against the examples repo. 

There are also a few independent examples beginning to pop up, e.g. https://github.com/rioscesar/terraform-oci-modules/tree/master/paas-on-oci (this is not maintained by Oracle or HashiCorp, contact the repo owner if you have questions)

Also FYI: `oraclepaas` provider specific issues at can be opened https://github.com/terraform-providers/terraform-provider-oraclepaas, and `oci` issues at https://github.com/oracle/terraform-provider-oci
