### ISSUE TITLE
Cannot Create Storage in Terraform Provider 

### ISSUE THREAD

**Issue by tjkervin** [terraform-providers/terraform-provider-opc#123]
Hello,

I am unable to get the storage resources working within the OPC provider. The error can be seen bellow, but it's a basic unable to authenticate error. This looks like it has to be a configuration issue on by end, but i've tried many combinations of solutions, and followed the configuration guide from the site listed below, but can't get anything to work

https://medium.com/oracledevs/managing-oracle-cloud-infrastructure-object-storage-classic-containers-and-objects-using-terraform-9b1a44fdb8b

I am able to authenticate using the REST api by executing the curl seen below (username and password redacted for obvious purposes:

curl -H "X-Storage-User: Storage-ourorg:user" -H "X-Storage-Pass: password" https://ourorg.storage.oraclecloud.com/auth/v1.0

That part works, but when I set the appropriate fields in terraform I get an invalid user name and password. 

1) Based on the curl provided, and the terraform 

2) Is there anything I can do to troubleshoot. Our IDP is different then the storage id, which should be handled by setting the storage_service_id variable, but that is not seemingly being honored. 

It's worth noting that I can run the plan, and execute applies (minus the storage resource) without these variables set. So it does seem to be this specific rest call that is  not working. 

Any advice would be greatly appreciated here. 

### Terraform Version
11.6

### Affected Resource(s)
- opc_storage_container

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
provider "opc" {
    storage_endpoint   = "https://ourorg.storage.oraclecloud.com"
    storage_service_id = "ourorg"
}

resource "opc_storage_container" "database" {
  name = "database"
}
```

### Debug Output
Error: Error refreshing state: 1 error(s) occurred:

* provider.opc: 401: Invalid user id or password

### Expected Behavior
What should have happened?

### Actual Behavior
What actually happened?

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by scross01** [comment]
You need to include the `user` and `password` fields in the `provider` definition, or set the `OPC_USERNAME` and `OPC_PASSWORD` environment variables.

see https://www.terraform.io/docs/providers/opc/index.html

e.g.

```hcl
provider "opc" {
  user = "user@example.com"
  password = "Pa55_Word"
  storage_endpoint = "https://ourorg.storage.oraclecloud.com"
  storage_service_id = "ourorg"
}
```

**Comment by tjkervin** [comment]
Here is a little more information as well. I'm using the same Terraform state to define compute instances, as well as storage. My OPC account has a service instance ID associated with it, which I have to use as the Identity Domain variable over the actual Identity Domain variable, as this is what the REST API uses to access our domain. I'm not sure if that is getting in the way here, or if that is completely irrelevant. Just wanted to bring it to the attention of this thread.
