### ISSUE TITLE
Getting public key value of uploaded key

### ISSUE THREAD

**Issue by nyamaguc** [terraform-providers/terraform-provider-opc#128]
Hi 

Is it possible to get the “key” value of an existing key ?
 
When I’m trying to get the public SSH Key of an existing Key, I’m getting the below error message.
	Error: data.opc_compute_ssh_key.key1: Provider doesn't support data source: opc_compute_ssh_key
 
Sample code to get the data of an existing code:
data "opc_compute_ssh_key" "key1" {
  name = "/Compute-*********/vikram.shirur@oracle.com/Vikram_LT"
}
 
output "opc_compute_ssh_key_key1_details" {
  value = "${data.opc_compute_ssh_key.key1.key}"
}
 
In one of the automation tool that we are developing, the user passes the 3 part name as the input.

### Terraform Version

[~]$ terraform -v
Terraform v0.11.7

### Affected Resource(s)
opc_compute_ssh_key 

### Terraform Configuration Files
Is it possible to get the “key” value of an existing key ?
 
When I’m trying to get the public SSH Key of an existing Key, I’m getting the below error message.

	Error: data.opc_compute_ssh_key.key1: Provider doesn't support data source: opc_compute_ssh_key
 
Sample code to get the data of an existing code:
data "opc_compute_ssh_key" "key1" {
  name = "/Compute-*********/vikram.shirur@oracle.com/Vikram_LT"
}
 
output "opc_compute_ssh_key_key1_details" {
  value = "${data.opc_compute_ssh_key.key1.key}"
}

### Debug Output
None. 

### Panic Output
None. 

### Expected Behavior
Get actual public key content. 

### Actual Behavior
	Error: data.opc_compute_ssh_key.key1: Provider doesn't support data source: opc_compute_ssh_key

### Steps to Reproduce
 `terraform apply`

### Important Factoids
None. 

### References
None

**Comment by scross01** [comment]
This will need an addition of an `opc_compute_ssh_key` data source implementation

**Comment by mbfrahry** [comment]
Hey @nyamaguc, @scross01 just added `opc_compute_ssh_key` as a datasource and it will be in the next release of the OPC provider. I'm closing this issue but feel free to reopen if you have any additional questions

**Comment by scross01** [comment]
@nyamaguc the new provider release v1.1.2 supports the `opc_compute_ssh_key` data source
