### ISSUE TITLE
add opc_compute_orchestration resource

### ISSUE THREAD

**Issue by scross01** [terraform-providers/terraform-provider-opc#14]
Add support for the managing native [Orchestrations](https://docs.oracle.com/cloud/latest/stcomputecs/STCSA/api-Orchestrations.html) for Oracle Compute Cloud

Usage would be similar to the way the aws provider handles cloud formation templates e.g. (for illustration purposes only)

```tf
resource "opc_compute_orchestration" "instance-orchestration" {
  name = "instance-orchestration"
  description = "my instance creation orchestration"
  schedule {
    start_time = "2017-06-20T12:00:00Z"
    stop_time = "2017-06-26T12:00:00Z"
  }
  
  vars {
    context = "/Compute-${var.domain}/${var.user}"
  }

  object_plan = <<OPLAN
{
  "obj_type": "launchplan",
  "ha_policy": "active",
  "label": "instance1",
  "objects": [
    {
      "instances": [
        {
          "shape": "oc3",
          "label": "instance1",
          "imagelist": "/oracle/public/compute_oel_6.4_2GB",
          "name": "$${content}/primary_webserver"
        }
      ]
    }
  ]
}
OPLAN
}
```

**Comment by kernell128** [comment]
Nice Stephen, just an question if we add tree instances on this launch plan, we will be able to:
 - force then run on different hosts relationship att,
 - stop/start independently (e.g. - just webserver2?)

**Comment by grubernaut** [comment]
Hey @kernell128 + @scross01,

Been debating whether or not to add `orchestrations` to OPC internally, and it's currently still up in the air. 

The main counter-point to adding `orchestrations` is the exact reasoning that @kernell128 listed in their second bullet point. Creating an orchestration resource with Terraform will disallow users from managing _any_ child resources created via the `orchestration` resource. Users could, however, `import` each resource created via the orchestration manually, but that would create significant problems if the orchestration resource was deleted/removed/modified.

ie: User deletes the `orchestration` resource, Terraform will delete everything the `orchestration` resource created, then on the subsequent plan/apply, Terraform will attempt to recreate the manually imported instance, as it no longer exists. 

I believe ultimately we'll end up adding an `orchestrations` resource, but will have to be extremely explicit that it should only be used as a _single_ resource, and child resources created from the orchestration will not be able to be managed via Terraform effectively. 

Perhaps, in the future, some aspiring OSS developer will create an OPC Orchestrations JSON file to Terraform HCL converter tool, but that's not a thing _yet_ :wink:

**Comment by nagulako** [comment]
@grubernaut  - For start and stop - perhaps we can use the "status" attribute? 

opc_compute_orchestration_resource "ol1" {

  name = "ol1"
  storage = "${opc_compute_storage....}"
  shape, size ...etc
  status = "running | stopped" << This could determine if the instance is running or not?
}

In this case - storage, network objects are created outside of the Orchestration resource, and can be managed independently i.e - when the orchestration stops - it doesn't destroy the storage or network objects (which is what I believe you're saying)  and only stops the instance?

Today  in OPC - we can create orchestrations for Storage, Sec Rules etc.  For an initial enhancement though - having the instance orchestration will go a long way IMHO.

**Comment by grubernaut** [comment]
Hey @nagulako,

You can currently stop/start an instance with Terraform via the `desired_state` attribute, and verify the state with the `state` attribute. 

My main point, is that creating an Orchestration resource in OPC creates anywhere from 1 to many child resources as a result of the Orchestration being ran. And Terraform currently cannot support creating child resources from a single parent resources, or in other words, Terraform cannot support nested resources. So, when a user creates an Orchestrations resource with Terraform, there will only be one object in Terraform's statefile, the Orchestration resource. 

We've discussed internally though, and are working on adding an instance resource that is created via the Orchestrations API, but it will be limited to creating a single OPC instance for each individual orchestration resource. Imagine, `opc_compute_orchestrations_instance`.

**Comment by nagulako** [comment]
I like the idea of  opc_compute_orchestrations_instance.

**Comment by ado1** [comment]
I like the Idea of the OPC Orchestrations JSON file to Terraform HCL converter tool. some thing like opc_compute_orchestrations_instance will create a nested Management (to avoide the term orchestrations in this case) between the Terraform HCL and the OPC Orchestrations which will bring a huge complexity.
Could somebody explain what functionality is/gets lost by not implementing a thing like opc_compute_orchestrations_instance? 

e.g. OCP PaaS has NO orchestrations for the underlaying IaaS resources as well.

**Comment by scross01** [comment]
v1.0.1 adds initial support the creating instances with orchestrations

See this overview for more details.
https://medium.com/oracledevs/terraform-and-oracle-cloud-infrastructure-classic-orchestrations-e0fd39580f1e
