### ISSUE TITLE
Timeouts should be configurable for storage attachments

### ISSUE THREAD

**Issue by mtjakobczyk** [terraform-providers/terraform-provider-opc#170]
Hi there,

under heavier load and complex infrastructures we have been experiencing longer provisioning for selected resources. This is all fine, but we hit Terraform timeouts from time to time. Although storage attachments are eventually successfully created, Terraform times out on the default 30-second-long timeout. We need to be able to override this default timeout for opc_compute_storage_attachment resource. 

```
Error: Error applying plan:

1 error(s) occurred:

* module.workers.opc_compute_storage_attachment.vm_dockervolume_attachment[2]: 1 error(s) occurred:

* opc_compute_storage_attachment.vm_dockervolume_attachment.2: Error creating StorageAttachment: Timeout after 30 seconds waiting for storage attachment to be attached
```

### Terraform Version
Terraform v0.11.13
+ provider.opc v1.3.4

### Affected Resource(s)
- opc_compute_storage_attachment

This resource needs to support an optional timeouts config block e.g.

### Terraform Configuration Files
```hcl
resource "opc_compute_storage_attachment" "vm_dockervolume_attachment" {
   ...
  timeouts {
    create = "2m"
    delete = "5m"
  }
}
```

### References
- https://github.com/terraform-providers/terraform-provider-opc/issues/155

**Comment by mbfrahry** [comment]
Hey @mtjakobczyk. Thanks for opening this issue This support just went out the door in the latest version of the provider `1.3.7`. Feel free to reopen this if you continue to see issues.
