### ISSUE TITLE
Storage snapshot restoration error

### ISSUE THREAD

**Issue by tsgmanh** [terraform-providers/terraform-provider-opc#25]
Hi there,

I am trying to restore couple of snapshots and got some strange error. any body is aware of this error?. when  I commented “collocated  = true” in my scripts then  snapshots was restored successfully. 

2 error(s) occurred:

* opc_compute_storage_volume.vol-data: 1 error(s) occurred:

* opc_compute_storage_volume.vol-data: Error creating storage volume demo4d-st-data01: 400: {"message": "Volume properties incompatible with snapshot properties"}
* opc_compute_storage_volume.vol-boot: 1 error(s) occurred:

* opc_compute_storage_volume.vol-boot: Error creating storage volume demo4d-st-boot01: 400: {"message": "Volume properties incompatible with snapshot properties"}

  “collocated  = true” worked last week.  After I commented “collocated  = true”,   snapshots was restored successfully. 

This is my terraform scripts,

```
# snapshot
resource "opc_compute_storage_volume_snapshot" "base" {
  name        = "${var.snap_boot_name}"
 collocated  = true
  description = "Demo"
  tags        = "${var.snp_boot_tags}"
  volume_name = "${var.src_vol_boot}"
}

# restore
resource "opc_compute_storage_volume" "vol-boot" {
  name        = "${var.restore_boot_vol_name}"
  bootable    = true
  image_list  = "/oracle/public/OL_7.2_UEKR4_x86_64"
  description = "Demo"
  size        = 12
  tags        = "${var.snp_boot_tags}"
  snapshot_id    = "${opc_compute_storage_volume_snapshot.base.snapshot_id}"
  image_list_entry = 1
}
```

**Comment by tsgmanh** [comment]
is this an error we can fix or is it a bug?

**Comment by grubernaut** [comment]
Hey @tsgmanh, we haven't started looking into this one yet, unfortunately. We should have more information for you when we do though. I believe @tombuildsstuff know's the most about storage volumes in OPC, but we're currently at a company retreat this week, and should know more next week. Thanks!

**Comment by tsgmanh** [comment]
Did anybody get a chance to look into this.  

Another thing which  I have to check  is on the timeout parameter. 
I see snapshot creation  has a timeout of 1200s whereas  snapshot restoration has only 600s.  can we set a common parameter  for all the resources. basically  I need to increase the timeout, since the restoration is failed due to that

**Comment by grubernaut** [comment]
Hey @tsgmanh, sorry for the delay looking into this for you. 

I'm getting the following error from creating a storage_volume from a snapshot with the parameters you specified above: 
```
Error applying plan:

1 error(s) occurred:

* opc_compute_storage_volume.test: 1 error(s) occurred:

* opc_compute_storage_volume.test: Error creating storage volume boot-from-snapshot: 400: {"message": "Only one of (imagelist, machineimage, snapshot, snapshot_id) needs to be specified."}
```

If I remove `image_list` and `image_list_entry` from the storage volume, however, then it works as expected, even with `collocated = true`. 

Are you able to try this again with the latest version of the OPC provider, and Terraform `v0.10.0`? Thanks, and apologies again for taking so long to dive into.

**Comment by tsgmanh** [comment]
This is working for me. with terraform v0.10.0 and provider v0.1.2 everything is good. thanks.

**Comment by grubernaut** [comment]
Awesome, glad to hear it! Please let us know if you have any further issues!
