### ISSUE TITLE
Importing Private Image crashes terraform

### ISSUE THREAD

**Issue by nagulako** [terraform-providers/terraform-provider-opc#26]
Hi there,

### Terraform Version
0.9.11

### Affected Resource(s)
Please list the resources as a list, for example:
- opc_compute_image_list_entry

### Terraform Configuration Files
none.  Just the credentials and then a test to import the image resource.
```

### Debug Output
https://gist.github.com/nagulako/dd89c2360f00b4503c92ec1e2beb1d0d

### Panic Output
https://gist.github.com/nagulako/316d8c90bd3847fd27b503d453e4b986

### Expected Behavior
Should have created a resource inside terraform i.e imported existing resource.

### Actual Behavior
crash

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1.  Create a private image from the console (in this case, it was SUSE Linux 11.4
2.  Use terraform import to import that image entry.  Entry crashes.

**Comment by scross01** [comment]
@nagulako  just out of interest, why be are you trying to import an `opc_compute_image_list_entry`? Doing an import will bring the resource under Terraform control, and a subsequent `terraform destroy` will delete the image list entry completely.  If you are just trying to reference some details of an existing image list entry elsewhere in your config then I suspect what is really needed is a `opc_compute_image_list_entry` **Data Source**
