### ISSUE TITLE
Provisioner remote-exec  using  in modules

### ISSUE THREAD

**Issue by tsgmanh** [terraform-providers/terraform-provider-opc#32]
I am creating few opc instance  using the modules concept so that I can reuse my module  any time. After the instance creation  has been completed then I want to run few remote-exec to copy few files and do the installation of application. below is the snippet of  my code. unfortunately its not working, can any body please help.

main.tf
======
```
module "instance" {
---
---
}

resource "null_resource" "cluster" {
  connection {
    user        = "user"
    host        = "${element(var.inst_ips, count.index)}"
    type        = "ssh"
    private_key = "${file("id_rsa")}"
    timeout     = "10m"
  }

  provisioner "file" {
    source      = "${path.module}/scripts/"
    destination = "/src/"
  }

  provisioner "remote-exec" {
    inline = [
      "chmod +x /src/setup.sh",
      "/src/setup.sh",
    ]
  }
}
```

module/instance/main.tf

```
resource "opc_compute_instance" "opc-inst" {
  count = "${length(var.inst_name)}"
  name  = "web-${format("%03d", count.index+1)}-${element(var.inst_name, count.index)}"
  label = "${var.label}"
  shape = "${var.shape}"
  networking_info {
    index      = 0
    ip_network = "${var.ip_network}"
    ip_address = "${element(var.inst_ips, count.index)}"
    vnic_sets  = ["${var.vnic_sets}"]
    vnic       = "${var.vnic}"
    nat = [ "${var.nat}" ]
    name_servers   = "${var.rfs_ns}"
    search_domains = "${var.search_domains}"
  }

  ssh_keys = ["sshkey"]

  storage {
    volume = "${var.boot_disk}"
    index  = 1
  }

  storage {
    volume = "${var.data_disk}"
    index  = 2
  }

  boot_order = [1]
}
```

**Comment by scross01** [comment]
A couple of thoughts/comments:
- it looks like you are creating everything within a private IP network - is the instance/environment where you are running Terraform also connected to (or route-able to) the private IP network so Terraform can connect to the instances?
- I don't see any direct dependency between the `null_resource` and the instances created by the module - it's possible the provisioning is trying to run before the instance is created.  Try adding a [`triggers`](https://www.terraform.io/docs/provisioners/null_resource.html#triggers) block with the list of instance ids.

**Comment by tsgmanh** [comment]
Yes. I have a node dedicated  for terraform and it is part of the same ip network. 

Now I have the removed the  connection and remote-exec lines from the main.tf and added inside the modules/instance/main.tf and its working now.

**Comment by scross01** [comment]
Great. closing the issue
