### ISSUE TITLE
snapshot restoration timeout error

### ISSUE THREAD

**Issue by tsgmanh** [terraform-providers/terraform-provider-opc#34]
I am creating  opc instances and for that I created a single main.tf file which will do three things, a) restore a boot disk from a snapshot d) restore data disk from snapshot 3) create an instance from all those snapshot restored disk. but during restoration I see a timeout error. restoration is happening for only 600  seconds and then I see a  snapshot error. only boot disk is restored.

a) can we increase the timeout parameter from 600 to some x seconds.?
b) or can we set a sleep between snapshot restore resource & opc instance resource in terraform so that instance creation will start only once snapshot have restored successfully. I tried using  below sleep command after snapshot restore but didn't provide any luck.
 provisioner "local-exec" {
  command = "sleep 1000"

}

below is the error I got.

* module.snapshot-restore.opc_compute_storage_volume.demo-final-dt: 1 error(s) occurred:

* opc_compute_storage_volume.demo-final-dt: Error creating storage volume demo-dev-001-data: Timeout waiting for storage volume demo-dev-001-data to become available.

can anybody please help on this quickly. I am fully struck due to this.

**Comment by tsgmanh** [comment]
any  inputs on this please?

**Comment by grubernaut** [comment]
Hey @tsgmanh, thanks for the issue! 

Going to tag this as an enhancement to add timeout configuration to the snapshot resource.

**Comment by grubernaut** [comment]
Closed via #41
