### ISSUE TITLE
Can't create storage volume with SSD storage

### ISSUE THREAD

**Issue by scross01** [terraform-providers/terraform-provider-opc#37]
### Terraform Version
0.9.11

### Affected Resource(s)
- opc_compute_storage_volume

### Terraform Configuration Files
```hcl
resource "opc_compute_storage_volume" "test" {
  name = "storageVolume1"
  size = 10
  storage_type = "/oracle/public/storage/ssd/gpl"
```

The `storage_type` attribute has a validation that [only allows Default and Latency storage](https://github.com/terraform-providers/terraform-provider-opc/blob/master/opc/resource_storage_volume.go#L43)

`/oracle/public/storage/ssd/gpl` needs to be added as an additional storage type.

**Comment by scross01** [comment]
Maybe the validation should be removed entirely to allow for other/future storage types, and a new storage_properties data source could be added.

**Comment by scross01** [comment]
Rather than having a [hard coded list of supported storage types](https://github.com/terraform-providers/terraform-provider-opc/blob/master/opc/resource_storage_volume.go#L43) in the provider I think the `storage_type` attribute should be opened up to allow any string as the available storage options will vary by domain

a `opc_compute_storage_properties` data source for could be added to query for the available [storage types](https://docs.oracle.com/en/cloud/iaas/compute-iaas-cloud/stcsa/op-property-storage-%7Bcontainer%7D--get.html)

**Comment by grubernaut** [comment]
@scross01 I can get behind that, however, just want to clarify why we have the validation function in place currently... 
Validation functions are ran during `plan` time, thus strengthening the contract that "if the plan succeeds, the apply is likely to also succeed". If a user attempts to create a storage resource with an unsupported storage type currently, they'll know during `plan` time, which has a huge benefit for users who use a CI system during collaboration. It's a fairly common setup to run `terraform plan` and verify the output succeeds during a PR to a DVCS, inside of a CI pipeline. However, this could create a situation where a user believes their configuration will work after a successful `plan`, yet fails halfway through the `apply`, leaving some resources created, and some in a failed state. 

i'm happy to remove the validation of the `storage_type` attribute, just wanted to clarify on why the strict validation is in place. With a data source, we can export a list of supported storage_types for the user's environment, but only if that's accessible via the API. 
Then the resulting conditional would look like:
```hcl
data "opc_compute_storage_properties" "foo" {
}

resource "opc_compute_storage_volume" "bar" {
  // ....
  storage_type = "${contains(data.opc_compute_storage_properties, var.desired_storage_type) ? var.desired_storage_type : var.known_fallback_storage_type}"
}
```
Where a user would still need to know of at least _one_ storage type that succeeds prior to creating the storage volume. Another way to use the data source would be to use the conditional for the `count` parameter though. Eg: 
```hcl
resource "opc_compute_storage_volume" "bar" {
  // ....
  count = "${contains(data.opc_compute_storage_properties, var.desired_storage_type) ? 1 : 0}"
}
```
Which will only create the storage volume if the desired `storage_type` is available for the domain. However, this will silently fail for the user, as the resource will not be created, but Terraform will successfully `apply` all of the resources.
