### ISSUE TITLE
userdata template script- opc instance

### ISSUE THREAD

**Issue by tsgmanh** [terraform-providers/terraform-provider-opc#38]
Hi, need an help.

I am trying to pass some userdata to my instance during creation and getting some error during  running. I am creating multiple instance and I need to run this userdata for each instance.

```
data "template_file" "userdata" {
template = "bootstrap.sh"
  vars {
    private_ips = "${element(var.inst_ips, count.index)}"
  }}
( private ip will pass as a variable input to my bootstrap.sh script)
resource "opc_compute_instance" "opc-inst" {
  count = "${length(var.inst_name)}"
  name  = "web-${format("%03d", count.index+1)}-${element(var.inst_name, count.index)}"
  label = "${var.label}"
  shape = "${var.shape}"
 instance_attributes = "${data.template_file.userdata.rendered}"

  networking_info {
    index          = 0
    ip_network     = "${var.ip_network}"
    ip_address     = "${element(var.inst_ips, count.index)}"
    vnic_sets      = ["${var.vnic_sets}"]
    vnic           = "${var.vnic}"
    nat            = ["${var.nat}"]
    name_servers   = "${var.rfs_ns}"
    search_domains = "${var.search_domains}"
  }
```

below  is the error I got. can anybody please help

```
* module.instance.opc_compute_instance.opc-inst[2]: "instance_attributes" contains an invalid JSON: invalid character 'b' looking for beginning of value
* module.instance.opc_compute_instance.opc-inst[0]: "instance_attributes" contains an invalid JSON: invalid character 'b' looking for beginning of value
* module.instance.opc_compute_instance.opc-inst[1]: "instance_attributes" contains an invalid JSON: invalid character 'b' looking for beginning of value
```

**Comment by scross01** [comment]
Your template is just creating a sting with the value "bootstrap.sh" - If "bootstrap.sh" is supposed to be local template file then you need to reference it as a file - see the [`template_file`](https://www.terraform.io/docs/providers/template/d/file.html) example usage. e.g.

```
template = "${file("${path.module}/bootstrap.sh.tpl")}"
```

**Comment by tsgmanh** [comment]
Thanks. let me make more clear on my requirement.

I am creating multiple instance using the module  method and where I need to pass a shell script to  be executed during instance booting time. the shell scripts need some variables as input [ like the IP address of each opc instance, hostname etc ],. I am  trying to achieve it through data template option. my question is now how to pass the each instance details(variables) to the script. I just tried using below method and  it is not working.

data "template_file" "userdata" {
  template = "${file("${path.module}/bootstrap.sh")}"

  vars {
    hostname = "$${var.hostname}"
     private_ip = "$${var.inst_ips}   [* not sure to how to pass this value dynamically, can we pass a list here]. I assumed all my below declared variable can reuse here.
  }
}

# creating a opc compute instance
resource "opc_compute_instance" "opc-inst" {
  count = "${length(var.inst_name)}"
 name  = "${element(var.inst_name, count.index)}"
 hostname  = "${element(var.hostname, count.index)}"
   tags        = ["${var.env_sdn_app_tags}"]
  label = "${var.label}"
  shape = "${var.shape}"
 instance_attributes = "${data.template_file.userdata.rendered}"

  networking_info {
    index          = 0
    ip_network     = "${var.ip_network}"
    ip_address     = "${element(var.inst_ips, count.index)}"
    vnic_sets      = ["${var.vnic_sets}"]
    vnic           = "${var.vnic}"
    nat            = ["${var.nat}"]
    name_servers   = "${var.rfs_ns}"
    search_domains = "${var.search_domains}"
  }

**Comment by tsgmanh** [comment]
another doubt, can we try using opc-init scripts also?

data "template_file" "userdata" {
  template = <<EOF
{"userdata": {"pre-bootstrap": { "script": "hostname=$(curl -s http://192.0.0.192/latest/meta-data/local-hostname)" .......]}}}
EOF
}

fetching the all the details from opc meta deta and passing it as input to  my scripts. thought please?

**Comment by scross01** [comment]
Yes you can use the pre-bootstrap scripts in the opc-init userdata to configure the instance.

**Comment by tsgmanh** [comment]
thanks,  but when I pass  the variable to scripts after fetching from metadata its not passing currently. 

just an example as below.

data "template_file" "userdata" {

  template = <<EOF
{"userdata": {"pre-bootstrap": { "script": ["hostname=$(curl -s http://192.0.0.192/latest/meta-data/local-hostname)","./bootstrap.sh]}}}
EOF
}

I am passing my hostname to my bootstrap.sh script. however its not passing correctly. am I missing anything?

**Comment by scross01** [comment]
You can check `/var/log/opc-compute/opc-init.log` for any opc-init errors. How are you getting the ./bootstrap.sh script onto the instance?  If you are trying to upload using the Terraform provisioner then it won't in place at the time `opc-init` runs. To execute a script from file rather than individual commands from opc-init you can try using the [`scriptURL`](https://docs.oracle.com/en/cloud/iaas/compute-iaas-cloud/stcsg/automating-instance-initialization-using-opc-init.html#GUID-E3A674C1-855B-4AD4-BB3E-A4A8F24189E3) option.

I don't think you can combine `script` and `scriptURL` in opc-init, so have the bootstrap.sh script get the required vars from the meta-data within the script rather than passing environment variables (this approach should work for regardless of if you execute the script through opc-init or the terraform provisioners

```bash
#!/bin/bash
hostname=$(curl -s http://192.0.0.192/latest/meta-data/local-hostname)
echo $hostname
```

**Comment by tsgmanh** [comment]
sorry for the delayed response. its working for  me now. please close this.

**Comment by tombuildsstuff** [comment]
Thanks for confirming @tsgmanh - closing.
