### ISSUE TITLE
add a `max_retries` provider option

### ISSUE THREAD

**Issue by tombuildsstuff** [terraform-providers/terraform-provider-opc#4]
_This issue was originally opened by @scross01 as hashicorp/terraform-provider-opc#7. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

A `max_retries` attribute is needed on the provider to set the maximum number of times an API call is retried, to handle cases where requests encounter transient failures, similar to https://www.terraform.io/docs/providers/aws/#max_retries

Default value would be `1`

**Comment by grubernaut** [comment]
Solved via: https://github.com/hashicorp/terraform-provider-opc/pull/12/files
