### ISSUE TITLE
OPC compute instance create based on docs fails with "Error creating instance"

### ISSUE THREAD

**Issue by craigbarrau** [terraform-providers/terraform-provider-opc#40]
### Terraform Version
`v0.9.11`

### Affected Resource(s)
Please list the resources as a list, for example:
- opc_compute_instance

### Terraform Configuration Files
```
# Configure the Oracle Public Cloud
provider "opc" {
  user            = "cloud.admin"
  password        = "OMITTED"
  identity_domain = "OMITTED"
  endpoint        = "https://api-Z53.compute.us6.oraclecloud.com/"
}


resource "opc_compute_ip_network" "test" {
  name                = "internal-network"
  description         = "Terraform Provisioned Internal Network"
  ip_address_prefix   = "10.0.1.0/24"
  public_napt_enabled = false
}

resource "opc_compute_storage_volume" "test" {
  name = "internal"
  size = 100
}

resource "opc_compute_instance" "test" {
  name       = "instance1"
  label      = "Terraform Provisioned Instance"
  shape      = "oc3"
  image_list = "/oracle/public/oel_6.7_apaas_16.4.5_1610211300"

  storage {
    volume = "${opc_compute_storage_volume.test.name}"
    index  = 1
  }

  networking_info {
    index          = 0
    nat            = ["ippool:/oracle/public/ippool"]
    shared_network = true
  }
}
```

### Debug Output
[https://gist.github.com/craigbarrau/9aeafbb9e261f207ebb14bd0a2cc348c](https://gist.github.com/craigbarrau/9aeafbb9e261f207ebb14bd0a2cc348c)

### Panic Output
N//A

### Expected Behavior
I would expect it to work as it is copied and pasted from [official doc example](https://www.terraform.io/docs/providers/opc/r/opc_compute_instance.html).

### Actual Behavior
It failed with an error:
```
* opc_compute_instance.test: Error creating instance /Compute-OMITTED/cloud.admin/instance1: 400: {"message": "seclist /Compute-OMITTED/default/default not found"}
```
Note: identity domain is omitted from the above output

### Steps to Reproduce
1. create tf file to match the provided example
2. replace `OMITTED` with details for a real `opc` instance
3. `terraform apply`

### Important Factoids
Nothing of significance

**Comment by scross01** [comment]
The instance creation is expecting a pre-existing `default` security list to exist in the domain - but the error indicates it's not present. The default security list typically just enables SSH.   To resolve in your environment either add an explicit reference to the different pre-defined security list, or add the creation of the security list to the Terraform configuration.

```tf
networking_info {
    index          = 0
    nat            = ["ippool:/oracle/public/ippool"]
    shared_network = true
    sec_lists      = [ "/Compute-OMITTED/cloud.admin/For-ssh-access" ]
}
```

**Comment by craigbarrau** [comment]
Thanks... same error though
```
* opc_compute_instance.test: Error creating instance /Compute-OMITTED/cloud.admin/instance1: 400: {"message": "seclist /Compute-OMITTED/cloud.admin/For-ssh-access not found"}
```

**Comment by craigbarrau** [comment]
Ah! Looks like this has done the trick...
```
sec_lists      = [ "For-ssh-access" ]
```

**Comment by craigbarrau** [comment]
Strangely the `terraform apply` worked but `terraform destroy` failed with this

```
* opc_compute_security_list.For-ssh-access: Error deleting security list For-ssh-access: 400: {"message": "Cannot delete seclist /Compute-OMITTED/cloud.admin/For-ssh-access because there are secrules associated with it or VMs using it."}
```

Why is it trying to delete `/Compute-OMITTED/cloud.admin/For-ssh-access` even though the correct value is `For-ssh-access`. Seems like it could be a bug. What do you think?

**Comment by craigbarrau** [comment]
nevermind... PEBCAK!

**Comment by craigbarrau** [comment]
Ah! Thanks for that explanation
So basically it does not have any implicit ordering but a reference creates
an explicit dependency? Nice!

**Comment by tombuildsstuff** [comment]
Yep - there's more details available on the Terraform website [including this quick summary](https://www.terraform.io/intro/index.html#resource-graph). It's also possible to do the same thing with a `depends_upon` attribute:

```
depends_on = ["opc_compute_security_list.sec_list1"]
```

.. however I find it's cleaner to use references between resources where possible as shown in my previous comment :)

Hope that helps!

**Comment by craigbarrau** [comment]
Thanks @tombuildsstuff for the tips!

**Comment by fharris** [comment]
Thank you guys!!! It worked perfect for me !! The explanation concerning the dependency with the security list was specially important! Cheers!
