### ISSUE TITLE
add opc_compute_image_list_entry as a data source

### ISSUE THREAD

**Issue by scross01** [terraform-providers/terraform-provider-opc#45]
To reference existing public, marketplace, and private images the `opc_compute_image_list` and `opc_compute_image_list_entry` needs to be available as data sources 

Target configuration could be something like (for illustration only):

```tf
data "opc_compute_image_list" "ubuntu-1604" {
  name = "/Compute-${var.domain}/${var.user}/Ubuntu.16.04-LTS.amd64.20160721"
}

data "opc_compute_image_list_entry" "ubuntu-1604-1" {
  image_list = ${opc_compute_image_list.ubuntu-1604.name}
  entry = 1
}

resource "opc_compute_storage_volume" "bootdisk" {
  name = "BootStorageVolume"
  bootable = true
  image_list = "${data.opc_compute_image_list_entry.ubuntu-1604-1.image_list}"
  image_list_entry = "${data.opc_compute_image_list_entry.ubuntu-1604-1.entry}"
  size = ${data.opc_compute_image_list_entry.ubuntu-1604-1.size}
}
``` 

Where `/Compute-${var.domain}/${var.user}/Ubuntu.16.04-LTS.amd64.20160721` is a pre-existing image in the domain

Note: `size` is not a native attribute of the image list entry, but would be useful if it was calculated from the underlying referenced machines image, so it can be used to provide the required size for the storage. Or maybe the right approach would be to add a separate `opc_compute_machine_image` data source .

**Comment by scross01** [comment]
This should help address #26 and #44

**Comment by gupraj** [comment]
Hi @scross01 -

You are awesome! Very helpful.

Thanks.
