### ISSUE TITLE
Import doesn't use tfvars file

### ISSUE THREAD

**Issue by lsarecz** [terraform-providers/terraform-provider-opc#49]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.9.11

### Affected Resource(s)
- opc_instance
- opc_compute_image_list
- opc_compute_ssh_key

I have not tested others, as I had the same issue for all three

### Terraform Configuration Files
There is no configuration file needed for import
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output
NA

### Panic Output
NA

### Expected Behavior
I expect that terraform doesn't prompt for variable values once there is a terraform.tfvars file available. It works for other commands as expected, but not for import as it prompts for the variables.

### Actual Behavior
Prompts for the variable values

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform import opc_compute_instance.compute_instance1 compute_instance1/6abcfdcb-0a19-45fc-ac52-815615dc59af`

### Important Factoids
NA

### References
NA

**Comment by lsarecz** [comment]
I have also tried to use -var-file=terraform.tfvars option, but it still prompted for the variable values.

My terraform.tfvars file looks like this:
user = "cloud.admin"
password = "Pa$$w0rd"
domain = "gse000xxxxx"
endpoint = "https://api-Z53.compute.us6.oraclecloud.com/"

I tested Terraform on Windows.

**Comment by grubernaut** [comment]
Hi @lsarecz, thanks for the issue!

I'm a little confused here though, as you stated: 
> There is no configuration file needed for import

However, without any Terraform config files, a `tfvar` file is useless. 

In order to use a `tfvars` file for the `opc` provider, the following configuration is a bare minimum: 
```
// main.tf
provider "opc" {
  user                   = "${var.user}"
  password           = "${var.password}"
  identity_domain = "${var.domain}"
  endpoint            = "${var.endpoint"
}
```
Using the example `tfvars` file that you listed above. 

Can you confirm that you're interpolating your variables correctly, as the example above shows? Thanks!

**Comment by lsarecz** [comment]
Hi @grubernaut, thanks a lot for your answer.

Yes, you are correct, I didn't have a config file, so that was the reason why the tfvars file was not used at all. Now with the minimum config file it works!

Thanks,
Lajos
