### ISSUE TITLE
import opc_compute_storage_volume_snapshot crashes

### ISSUE THREAD

**Issue by tombuildsstuff** [terraform-providers/terraform-provider-opc#6]
_This issue was originally opened by @nagulako as hashicorp/terraform-provider-opc#8. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

Hi there,

### Terraform Version
root@nvmk-sol-wls1:~/terraform_opc/opc/e18#  terraform -v
Terraform v0.9.5

### Affected Resource(s)
Please list the resources as a list, for example:
opc_compute_storage_volume_snapshot

### Terraform Configuration Files

Single command - no config file here.
terraform import opc_compute_storage_volume_snapshot.tf-nvmk-corente-sol1-snapshot tf-nvmk-corente-sol1-snapshot
t.

### Panic Output
https://gist.github.com/nagulako/a10e5ee928c8fef0ea8544cac2516ff2

### Expected Behavior
Imported the Storage snapshot.

### Actual Behavior
Crash

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
terraform import opc_compute_storage_volume_snapshot.tf-nvmk-corente-sol1-snapshot tf-nvmk-corente-sol1-snapshot

### Important Factoids
Oracle Public Cloud.

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
None

**Comment by kdvlr** [comment]
Can confirm it still exists in 0.9.8
