### ISSUE TITLE
terraform - Authorization token invalid error 

### ISSUE THREAD

**Issue by tsgmanh** [terraform-providers/terraform-provider-opc#65]
Hi,
I am getting following error when I ran terraform script. this error is getting after 30 minutes when i run the script.  The error is throwing during middle of restoring snapshot.

Terraform version - 0.10.0
Provider version - 0.1.2
My script is doing three things
a) creating a snapshot of an existing disk
b using the snapshot create a storage volume
c) using the storage volume then create an instance.
Error applying plan:
1 error(s) occurred:
module.snapshot-restore.opc_compute_storage_volume.opc-restore-data[0]: 1 error(s) occurred:
opc_compute_storage_volume.opc-restore-data.0: Error creating storage volume sp-demo-data: 401: {"message": "Authorization token is invalid"}

**Comment by tsgmanh** [comment]
just wanted to check, is there any update on this? thanks.

**Comment by tsgmanh** [comment]
I am getting this error frequently. it will be really great if I can get an update.

@grubernaut

**Comment by mbfrahry** [comment]
Hey @tsgmanh. @grubernaut, isn't available to work on this anymore but I'll start hammering away on this issue today. Thank you for your patience.

**Comment by scross01** [comment]
Fixed by #79
