### ISSUE TITLE
JCS and DBCS support?

### ISSUE THREAD

**Issue by omar2345** [terraform-providers/terraform-provider-opc#70]
Hi there,

Are there plans to create a provider for Oracle PaaS services such as:

[Java Cloud Service](https://docs.oracle.com/en/cloud/paas/java-cloud/jsrmr/rest-endpoints.html) (JCS) 
[Database Cloud Service](https://docs.oracle.com/en/cloud/paas/database-dbaas-cloud/csdbr/rest-endpoints.html) (DBCS)?

Thanks!

**Comment by grubernaut** [comment]
Hey @omar2345, 

You're in luck! We are currently working on adding these PaaS resources to the OPC provider, and should be added shortly to the provider. Thanks!
