### ISSUE TITLE
Clarification on the default Networking setting when networking_info block is not specified

### ISSUE THREAD

**Issue by lucassrg** [terraform-providers/terraform-provider-opc#74]
### Terraform Version
Terraform v0.10.2

### Affected Resource(s)
- opc_instance

### Expected Behavior
According to the `opc_compute_instance` [documentation](https://www.terraform.io/docs/providers/opc/r/opc_compute_instance.html), the  `networking_info` [argument](https://www.terraform.io/docs/providers/opc/r/opc_compute_instance.html#networking_info) is **Optional**:
 
```
networking_info - (Optional) Information pertaining to an individual network interface to be created and attached to the instance. See Networking Info below for more information.
```

I clearly understand that we have the attribute `shared_network` within the `networking_info` block to specify the network setting. However, when we do not specify the `networking_info` block on the configuration template, Terraform assumes that ***Shared Network*** should be setup. If this is the expected behavior, the documentation should explicitly make that clear, because through the OPC Console you **always** have to choose which network setting you want to use: Shared network, IPNetworks or both.

I believe we should have that clear at least in the documentation to better enforce the semantics for the network.

### Terraform Configuration Files
The template above shows exactly that issue. 

```hcl
provider "opc" {
  user            = "${var.user}"
  password        = "${var.password}"
  identity_domain = "${var.domain}"
  endpoint        = "${var.endpoint}"
}

resource "opc_compute_instance" "instance1" {
  name       = "example-instance1"
  label      = "My Oracle Linux 7.2 UEK3 Server"
  shape      = "oc3"
  image_list = "/oracle/public/OL_7.2_UEKR3_x86_64"
  ssh_keys   = ["${opc_compute_ssh_key.sshkey1.name}"]
}

resource "opc_compute_ssh_key" "sshkey1" {
  name    = "example-sshkey1"
  key     = "${file(var.ssh_public_key_file)}"
  enabled = true
}

resource "opc_compute_ip_reservation" "ipreservation1" {
  parent_pool = "/oracle/public/ippool"
  permanent   = true
}

resource "opc_compute_ip_association" "instance1-ipreservation" {
  vcable      = "${opc_compute_instance.instance1.vcable}"
  parent_pool = "ipreservation:${opc_compute_ip_reservation.ipreservation1.name}"
}
```

### References
Network_info: https://www.terraform.io/docs/providers/opc/r/opc_compute_instance.html#shared_network

**Comment by grubernaut** [comment]
Hey @lucassrg, absolutely agree!

Will update documentation for that now, and apologies for any issues this has caused you.

**Comment by grubernaut** [comment]
Updated on the live site: https://www.terraform.io/docs/providers/opc/r/opc_compute_instance.html#networking-info
