### ISSUE TITLE
Start/Stop instance - Desired State

### ISSUE THREAD

**Issue by carlomarini** [terraform-providers/terraform-provider-opc#78]
Hi there,

### Terraform Version
Terraform 0.10

### Affected Resource(s)
Please list the resources as a list, for example:
- opc_instance

Hi Could you please give an example on how is it possible to:

- Start, stop instance with Terraform

Thanks

carlo

**Comment by scross01** [comment]
You should be able to set the `desired_state` attribute in the instance resource to either `running` or `shutdown` to toggle an instance state.

@mbfrahry it looks like this attribute is missing from [docs](https://www.terraform.io/docs/providers/opc/r/opc_compute_instance.html)

**Comment by gupraj** [comment]
Hi @scross01  Thanks for update., Is this will work only in case of instance creation to make default state of newly created instance as running OR stop? Post instance creation how we can use terraform to stop and start .

**Comment by scross01** [comment]
You would need to update the .tf configuration with the new desired state and re-run `terraform apply`
