### ISSUE TITLE
Error initializing instance: Error during setup or launch

### ISSUE THREAD

**Issue by oakzaid** [terraform-providers/terraform-provider-opc#8]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

terraform -v
Terraform v0.9.8

### Affected Resource(s)
Please list the resources as a list, for example:
- opc_instance = terraform_instance

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

provider "opc" {
  user            = "${var.user}"
  password        = "${var.password}"
  identity_domain = "${var.domain}"
  endpoint        = "${var.endpoint}"
}

resource "opc_compute_instance" "terraform_instance" {
  count      = 3
  name       = "${format("instance%1d", count.index + 1)}"
  label      = "${format("instance%1d", count.index + 1)}"
  shape      = "oc3"
  image_list = "/Compute-${var.domain}/${var.user}/Ubuntu.16.04-LTS.amd64.20170330"
  ssh_keys   = ["${opc_compute_ssh_key.terraformKey.name}"]

  storage {
    index  = 1
    volume = "${opc_compute_storage_volume.terraform_bootable_storage.name}"
  }
}

resource "opc_compute_ssh_key" "terraformKey" {
  name    = "terraformKey"
  key     = "${file(var.ssh_publicKey_file)}"
  enabled = true
}

resource "opc_compute_ip_reservation" "reserve_ip" {
  count       = 3
  parent_pool = "/oracle/public/ippool"
  permanent   = true
  tags        = []
}

resource "opc_compute_ip_association" "instance_accociateIP" {
  count       = 3
  vcable      = "${element(opc_compute_instance.terraform_instance.*.vcable,count.index)}"
  parent_pool = "ipreservation:${element(opc_compute_instance.terraform_instance.*.name,count.index)}"
}

/*
resource "opc_compute_storage_volume" "storage_space" {
  name        = "terraform_storage_space"
  description = "creates a storage volume to attache separtly"
  size        = 10
}
*/

resource "opc_compute_storage_volume" "terraform_bootable_storage" {
  #count       = 3
  name        = "terraform_bootable_storage"
  description = "persistent bootable storage that is attached to this instance"
  size        = 10
}

#security stuff below

resource "opc_compute_sec_rule" "SSH_ACCESS" {
  name             = "SSH_ACCESS"
  source_list      = "seciplist:${opc_compute_security_ip_list.public_internet.name}"
  destination_list = "seclist:${opc_compute_security_list.SSH_ALLOW.name}"
  action           = "permit"
  application      = "${opc_compute_security_application.ssh_port.name}"
}

resource "opc_compute_security_application" "ssh_port" {
  name     = "ssh_port"
  protocol = "tcp"
  dport    = "22"
}

resource "opc_compute_security_association" "associate_SSH" {
  count   = 3
  name    = "associate_SSH"
  vcable  = "${element(opc_compute_instance.terraform_instance.*.vcable,count.index)}"
  seclist = "${opc_compute_security_list.SSH_ALLOW.name}"
}

resource "opc_compute_security_ip_list" "public_internet" {
  name       = "public_internet"
  ip_entries = ["0.0.0.0/0"]
}

resource "opc_compute_security_list" "SSH_ALLOW" {
  name                 = "SSH_ALLOW"
  policy               = "deny"    
  outbound_cidr_policy = "permit"
}

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

https://gist.github.com/oakzaid/82312e9d06101b6a98e015decc3856e0

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

all three resources should be created

### Actual Behavior
What actually happened?

i am trying to create multiple instances of the same instance but it gives me this error after creating one of them.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. terraform apply or TF_LOG=DEBUG terraform apply

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

i am running this in OPC

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by grubernaut** [comment]
Error message: 
```
* opc_compute_instance.terraform_instance.0: Error creating instance /Compute-domain/user@email.com/instance1: Error initializing instance: Error during setup or launch
```

I believe this is an upstream API issue. 
What do you think @scross01?

**Comment by scross01** [comment]
The error message "Error during setup or launch" seems to be coming from the Compute Cloud API,  reported during the [WaitForInstanceRunning()](https://github.com/hashicorp/go-oracle-terraform/blob/181f071554a111de0fde9799162796cbadefeaa8/compute/instances.go#L476).

**Comment by scross01** [comment]
@oakzaid Can you run the `apply` with debugging enabled

```
$ TF_LOG=DEBUG terraform apply
```

In the log output look for the `HTTP POST Req (/launchplan/):` entry and provide details of the following line with instance creation request payload

Something like:

```
2017/06/06 07:23:19 [DEBUG] plugin: terraform.exe: opc-provider (internal) 2017/06/06 07:23:19 [DEBUG] [go-oracle-terraform]: HTTP POST Req (/launchplan/):
2017/06/06 07:23:19 [DEBUG] plugin: terraform.exe:  {"instances":[{"attributes":null,"boot_order":null,"hostname":"","imagelist":"/oracle/public/OL_7.2_UEKR3_x86_64","label":"terraform-instance-1","name":"/Compute-mydomain/user@example.com/terraform-instance-1","networking":{"eth1":{"ipnetwork":"/Compute-mydomain/user@example.com/ipnetwork50"}},"reverse_dns":true,"shape":"oc3","storage_attachments":[],"sshkeys":[],"tags":null}]} 
```

**Comment by oakzaid** [comment]
i hope the below stuff helps and was what you requested Steve. Instance1
was created but nothing else.


opc_compute_instance.terraform_instance.0: Creating...
  attributes:                "" => "<computed>"
  availability_domain:       "" => "<computed>"
  desired_state:             "" => "running"
2017/06/27 10:56:37 [DEBUG] plugin: terraform: opc-provider (internal)
2017/06/27 10:56:37 [DEBUG] No meta timeoutkey found in Apply()
2017/06/27 10:56:37 [DEBUG] plugin: terraform: opc-provider (internal)
2017/06/27 10:56:37 [DEBUG] [go-oracle-terraform]:* HTTP POST Req
(/launchplan/):*
2017/06/27 10:56:37 [DEBUG] plugin: terraform:
 {"instances":[{"attributes":null,"boot_order":null,"hostname":"","imagelist":"/Compute-a430291/
ZABUSEINI@forsythe.com/Ubuntu.16.04-LTS.amd64.20170330
","label":"instance3","name":"/Compute-a430291/
ZABUSEINI@forsythe.com/instance3
","networking":{},"reverse_dns":true,"shape":"oc3","storage_attachments":[{"index":1,"volume":"/Compute-a430291/
ZABUSEINI@forsythe.com/terraform_bootable_storage
"}],"sshkeys":["/Compute-a430291/ZABUSEINI@forsythe.com/terraformKey
"],"tags":null}]}
2017/06/27 10:56:37 [DEBUG] root: eval: *terraform.EvalApply
2017/06/27 10:56:37 [DEBUG] apply:
opc_compute_instance.terraform_instance.0: executing Apply
2017/06/27 10:56:37 [DEBUG] root: eval: *terraform.EvalApply
2017/06/27 10:56:37 [DEBUG] apply:
opc_compute_instance.terraform_instance.1: executing Apply


opc_compute_instance.terraform_instance.1: Creating...

2017/06/27 10:56:37 [DEBUG] plugin: terraform: opc-provider (internal)
2017/06/27 10:56:37 [DEBUG] No meta timeoutkey found in Apply()
2017/06/27 10:56:37 [DEBUG] plugin: terraform: opc-provider (internal)
2017/06/27 10:56:37 [DEBUG] [go-oracle-terraform]: *HTTP POST Req
(/launchplan/):*
2017/06/27 10:56:37 [DEBUG] plugin: terraform:
 {"instances":[{"attributes":null,"boot_order":null,"hostname":"","imagelist":"/Compute-a430291/
ZABUSEINI@forsythe.com/Ubuntu.16.04-LTS.amd64.20170330
","label":"instance1","name":"/Compute-a430291/
ZABUSEINI@forsythe.com/instance1
","networking":{},"reverse_dns":true,"shape":"oc3","storage_attachments":[{"index":1,"volume":"/Compute-a430291/
ZABUSEINI@forsythe.com/terraform_bootable_storage
"}],"sshkeys":["/Compute-a430291/ZABUSEINI@forsythe.com/terraformKey
"],"tags":null}]}
2017/06/27 10:56:37 [DEBUG] plugin: terraform: opc-provider (internal)
2017/06/27 10:56:37 [DEBUG] No meta timeoutkey found in Apply()
2017/06/27 10:56:37 [DEBUG] plugin: terraform: opc-provider (internal)
2017/06/27 10:56:37 [DEBUG] [go-oracle-terraform]: HTTP POST Req
(/launchplan/):
2017/06/27 10:56:37 [DEBUG] plugin: terraform:
 {"instances":[{"attributes":null,"boot_order":null,"hostname":"","imagelist":"/Compute-a430291/
ZABUSEINI@forsythe.com/Ubuntu.16.04-LTS.amd64.20170330
","label":"instance2","name":"/Compute-a430291/
ZABUSEINI@forsythe.com/instance2
","networking":{},"reverse_dns":true,"shape":"oc3","storage_attachments":[{"index":1,"volume":"/Compute-a430291/
ZABUSEINI@forsythe.com/terraform_bootable_storage
"}],"sshkeys":["/Compute-a430291/ZABUSEINI@forsythe.com/terraformKey
"],"tags":null}]}
2017/06/27 10:56:37 [DEBUG] dag/walk: vertex "root", waiting for:
"meta.count-boundary (count boundary fixup)"
2017/06/27 10:56:37 [DEBUG] dag/walk: vertex "provider.opc (close)",
waiting for: "opc_compute_ip_association.instance_accociateIP[2]"
2017/06/27 10:56:37 [DEBUG] dag/walk: vertex
"opc_compute_security_association.associate_SSH[0]", waiting for:
"opc_compute_instance.terraform_instance[0]"
2017/06/27 10:56:37 [DEBUG] dag/walk: vertex
"opc_compute_ip_association.instance_accociateIP[1]", waiting for:
"opc_compute_instance.terraform_instance[2]"
2017/06/27 10:56:37 [DEBUG] dag/walk: vertex
"opc_compute_ip_association.instance_accociateIP[0]", waiting for:
"opc_compute_instance.terraform_instance[0]"
2017/06/27 10:56:37 [DEBUG] dag/walk: vertex "meta.count-boundary (count
boundary fixup)", waiting for:
"opc_compute_security_association.associate_SSH[1]"
2017/06/27 10:56:37 [DEBUG] dag/walk: vertex
"opc_compute_ip_association.instance_accociateIP[2]", waiting for:
"opc_compute_instance.terraform_instance[1]"
2017/06/27 10:56:37 [DEBUG] dag/walk: vertex
"opc_compute_security_association.associate_SSH[1]", waiting for:
"opc_compute_instance.terraform_instance[2]"

**Comment by scross01** [comment]
@oakzaid  I found the problem - the issue is with the instance configuration, all three instances are getting created referencing the same storage volume - `instance3` got created first and succeeds, then `instance1` tries to attache the same storage volume and fails - a block storage volume can only be attached to one instance. 

You need to define the `count` on the `opc_compute_storage_volume` (it's commented out in your config) and then reference the storage volume by the index in the instance resource:

```tf
  storage {
    index  = 1
    volume = "${element(opc_compute_storage_volume.terraform_bootable_storage.*.name, count.index)}"
  }
```

Also the overall configuration looks a bit odd, your instances is defined to launch with ephemeral instance storage (`image_list` is defined in the instance) but the comment for the storage resource indicate your trying to create the instance with persistent boot storage.  If you want persistent boot storage remove the `image_list` attribute from the `opc_compute_instance` update update the [`opc_compute_storage_volume`](https://www.terraform.io/docs/providers/opc/r/opc_compute_storage_volume.html) `terraform_bootable_storage`  to be a bootable volume by adding the `bootable`, `image_list` and `image_list_entry` attributes

```tf
resource "opc_compute_storage_volume" "terraform_bootable_storage" {
  count = 3
  name = "terraform_bootable_storage"
  description = "persistent bootable storage that is attached to this instance"
  bootable = true
  image_list= "/Compute-${var.domain}/${var.user}/Ubuntu.16.04-LTS.amd64.20170330"
  image_list_entry = 1
  size = 10
}
```

In the `opc_compute_instance` add

```
 boot_order = [ 1 ]
```

**Comment by grubernaut** [comment]
Thanks @scross01! Do you think this is something that can be passed onto the API team to make this error message a little clearer on why the instance failed to start?

**Comment by oakzaid** [comment]
Hi i have gotten this error now


Error applying plan:

5 error(s) occurred:

* opc_compute_ip_association.instance_accociateIP[1]: 1 error(s) occurred:

* opc_compute_ip_association.instance_accociateIP.1: Error creating ip
association between vcable c8d83bff-1d01-42bb-858d-3c6c60734e8e and parent
pool ipreservation:instance2: 404: {"message": "The IPReservation
Compute-a430291/ZABUSEINI@forsythe.com/instance2 does not exist"}
* opc_compute_ip_association.instance_accociateIP[2]: 1 error(s) occurred:

* opc_compute_ip_association.instance_accociateIP.2: Error creating ip
association between vcable e0e82aa6-4354-4c6b-929e-358107f8800b and parent
pool ipreservation:instance3: 404: {"message": "The IPReservation
Compute-a430291/ZABUSEINI@forsythe.com/instance3 does not exist"}
* opc_compute_security_association.associate_SSH[1]: 1 error(s) occurred:

* opc_compute_security_association.associate_SSH.1: Error creating security
association between vcable c8d83bff-1d01-42bb-858d-3c6c60734e8e and
security list SSH_ALLOW: 409: {"message": "Specified secassociation name
/Compute-a430291/ZABUSEINI@forsythe.com/associate_SSH already exists"}
* opc_compute_security_association.associate_SSH[2]: 1 error(s) occurred:

* opc_compute_security_association.associate_SSH.2: Error creating security
association between vcable e0e82aa6-4354-4c6b-929e-358107f8800b and
security list SSH_ALLOW: 409: {"message": "Specified secassociation name
/Compute-a430291/ZABUSEINI@forsythe.com/associate_SSH already exists"}
* opc_compute_ip_association.instance_accociateIP[0]: 1 error(s) occurred:

* opc_compute_ip_association.instance_accociateIP.0: Error creating ip
association between vcable 3ef91341-6902-49ea-9284-3a02837cfaaa and parent
pool ipreservation:instance1: 404: {"message": "The IPReservation
Compute-a430291/ZABUSEINI@forsythe.com/instance1 does not exist"}

**Comment by scross01** [comment]
The full config below should work.  

The `opc_compute_ip_association` parent_pool when set wrong, changed to

```
  parent_pool = "ipreservation:${element(opc_compute_ip_reservation.reserve_ip.*.name,count.index)}"
```

The `opc_compute_security_association` names need to be unique:

```
  name    = "${format("associate_SSH%1d", count.index + 1)}"
```

Made a similar change to `opc_compute_storage_volume`, not required, but good practice

```
  name        = "${format("terraform_bootable_storage%1d", count.index + 1)}"
```

Here's the complete config:

```tf
provider "opc" {
  user            = "${var.user}"
  password        = "${var.password}"
  identity_domain = "${var.domain}"
  endpoint        = "${var.endpoint}"
}

resource "opc_compute_instance" "terraform_instance" {
  count      = 3
  name       = "${format("instance%1d", count.index + 1)}"
  label      = "${format("instance%1d", count.index + 1)}"
  shape      = "oc3"
  image_list = "/Compute-${var.domain}/${var.user}/Ubuntu.16.04-LTS.amd64.20170330"
  ssh_keys   = ["${opc_compute_ssh_key.terraformKey.name}"]

  storage {
    index  = 1
    volume = "${element(opc_compute_storage_volume.terraform_bootable_storage.*.name, count.index)}"
  }
}

resource "opc_compute_ssh_key" "terraformKey" {
  name    = "terraformKey"
  key     = "${file(var.ssh_publicKey_file)}"
  enabled = true
}

resource "opc_compute_ip_reservation" "reserve_ip" {
  count       = 3
  parent_pool = "/oracle/public/ippool"
  permanent   = true
  tags        = []
}

resource "opc_compute_ip_association" "instance_accociateIP" {
  count       = 3
  vcable      = "${element(opc_compute_instance.terraform_instance.*.vcable,count.index)}"
  parent_pool = "ipreservation:${element(opc_compute_ip_reservation.reserve_ip.*.name,count.index)}"
}

/*
resource "opc_compute_storage_volume" "storage_space" {
  name        = "terraform_storage_space"
  description = "creates a storage volume to attache separtly"
  size        = 10
}
*/

resource "opc_compute_storage_volume" "terraform_bootable_storage" {
  count       = 3
  name        = "${format("terraform_bootable_storage%1d", count.index + 1)}"
  description = "persistent bootable storage that is attached to this instance"
  size        = 10
}

#security stuff below

resource "opc_compute_sec_rule" "SSH_ACCESS" {
  name             = "SSH_ACCESS"
  source_list      = "seciplist:${opc_compute_security_ip_list.public_internet.name}"
  destination_list = "seclist:${opc_compute_security_list.SSH_ALLOW.name}"
  action           = "permit"
  application      = "${opc_compute_security_application.ssh_port.name}"
}

resource "opc_compute_security_application" "ssh_port" {
  name     = "ssh_port"
  protocol = "tcp"
  dport    = "22"
}

resource "opc_compute_security_association" "associate_SSH" {
  count   = 3
  name    = "${format("associate_SSH%1d", count.index + 1)}"
  vcable  = "${element(opc_compute_instance.terraform_instance.*.vcable,count.index)}"
  seclist = "${opc_compute_security_list.SSH_ALLOW.name}"
}

resource "opc_compute_security_ip_list" "public_internet" {
  name       = "public_internet"
  ip_entries = ["0.0.0.0/0"]
}

resource "opc_compute_security_list" "SSH_ALLOW" {
  name                 = "SSH_ALLOW"
  policy               = "deny"
  outbound_cidr_policy = "permit"
}
```

**Comment by oakzaid** [comment]
After fixing some issues i ran into a new error i am receiving. I woul

Error applying plan:

1 error(s) occurred:

* opc_compute_security_list.SSH_ALLOW: 1 error(s) occurred:

* opc_compute_security_list.SSH_ALLOW: Error creating security list
SSH_ALLOW1 : 400: {"message": {"name": "Invalid construction for PathName:
\"/Compute-a430291/ZABUSEINI@forsythe.com/SSH_ALLOW1 \""}}

below is the code i am using

resource "opc_compute_security_list" "SSH_ALLOW" {
  name    = "${format("SSH_ALLOW%1d", count.index + 1)} "
  #name =  "SSH_ALLOW"
  policy               = "deny"
  outbound_cidr_policy = "permit"
}

**Comment by scross01** [comment]
@oakzaid your trying to reference the count index in the `name` but you don't have a `count` attribute set in the `opc_compute_security_list`.  Not sure why you are trying to it this way.   In the full example above the security list is only created once to enable SSH and all the instances reference it.  If you really intend to create multiple security lists with the same configuration specific to each instance you will also need to update the `opc_compute_security_association`.`seclist` to reference by the count index, in addition to adding the `count` to the `opc_compute_security_list` resource e.g.

```tf
  seclist = "${element(opc_compute_security_list.SSH_ALLOW.name, count.index)}"
```

**Comment by oakzaid** [comment]
Hi Steve,

i apologize when i added the changes you suggested i must have forgotten
something. I took the code you gave me above and ran it and it seems like
everything worked. Not sure what i forgot to add when you sent the last
code.

thanks again for all the help!

**Comment by oakzaid** [comment]
Hi Jake,

Everything is working great thanks!

**Comment by grubernaut** [comment]
Awesome, thanks!!
