### ISSUE TITLE
Storage vol addition in running OPC instance.

### ISSUE THREAD

**Issue by gupraj** [terraform-providers/terraform-provider-opc#82]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
- Terraform v0.10.4

### Affected Resource(s)
Please list the resources as a list, for example:
- opc_instance
- opc_storage_volume

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.
- While adding new storage volume, Instance recreate and with new storage volume.
- Unable to see orchestration for instance.

### Terraform Configuration Files
provider "opc" { 
user            = "*******" 
password        = "*******" 
identity_domain = "******" 
endpoint        = "https://compute.*******.oraclecloud.com/" 
} 

resource "opc_compute_storage_volume" "volume1" {
  size             = "13"
  description      = "Example bootable storage volume"
  name             = "boot-from-storage-example"
  bootable         = true
  image_list       = "/oracle/public/OL_6.4_UEKR4_x86_64"
  image_list_entry = 3
}

resource "opc_compute_storage_volume" "volume2" {
  size        = "4"
  description = "Example persistent storage volume"
  name        = "persistent-storage-example"
}

resource "opc_compute_storage_volume" "volume3" {
  size        = "4"
  description = "Example persistent storage volume"
  name        = "persistent-storage-example-vol3"
}

-- Newly added 
resource "opc_compute_storage_volume" "volume4" {
  size        = "2"
  description = "Example persistent storage volume"
  name        = "persistent-storage-example-vol4"
}

resource "opc_compute_instance" "instance1" {
  name  = "boot-from-storage-instance1"
  label = "Example instance with bootable storage"
  shape = "oc3"

  storage {
    index  = 1
    volume = "${opc_compute_storage_volume.volume1.name}"
  }

  storage {
    index  = 2
    volume = "${opc_compute_storage_volume.volume2.name}"
  }

storage {
    index  = 3
    volume = "${opc_compute_storage_volume.volume3.name}"
  }

-- Newly added 
storage {
    index  = 4
    volume = "${opc_compute_storage_volume.volume4.name}"
  }

  boot_order = [1]
}

### Debug Output
NA
### Panic Output
Instance recreated

### Expected Behavior
No, Expected new volume will get add in existing instance.

### Actual Behavior
Instance recreated with new volumn

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
terraform plan
terraform apply

Update .tf with new volumn
terraform apply

**Comment by scross01** [comment]
Modifying (add or remove) the instance storage volumes (other than the boot volume) should use the [storage attachment](https://docs.oracle.com/en/cloud/iaas/compute-iaas-cloud/stcsa/api-StorageAttachments.html) API to update the running instance rather than forcing the instance to be recreated

If the boot volume is changed then the instance would need to be recreated.

**Comment by gupraj** [comment]
Hi @scross01 , Thanks for reply. Checked storage attachment API, but still not sure how we can use as i did not used API earlier for OPC, If possible please share some used case. Thank you so much.

**Comment by fauzank** [comment]
Hi @scross01 The storage attachment points to rest based API what would be the resource name in terraform to use. I checked the documentation and couldnt find anything.

**Comment by scross01** [comment]
My comment on the API was intended to be development guidance for implementing a fix/change to so the compute instance resource can support dynamically adding/removing storage volumes   Until an update is available can could use the [opc cli utility](http://www.oracle.com/technetwork/topics/cloud/downloads/opc-cli-3096036.html) to attach the new storage volume to a running instance.

The storage volume can be added in the terraform config (but not added to the instance), and then use the cli attached the volume to the instance

```
$ opc compute storage-attachments add <index> <instance-name> <storage-volume-name>
```

You will probably then need to update the instance definition and do an import to bring the terraform config/state inline with the actual provisioned state.

**Comment by gupraj** [comment]
Thanks@scross01.

**Comment by scross01** [comment]
v1.1.0 of the provider adds a new `opc_compute_storage_attachment` resource that can be used to attach new block storage volumes to an existing instance. 

An example of using the `opc_compute_storage_attachment` resource for dynamically attaching storage volumes is covered in this article
https://medium.com/oracledevs/using-terraform-to-provision-oracle-cloud-infrastructure-classic-instances-with-persistent-block-ef47fb90c2b0
