### ISSUE TITLE
Error in instance JSON, unable to use two NAT IP within shared network configuration

### ISSUE THREAD

**Issue by gupraj** [terraform-providers/terraform-provider-opc#85]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Affected Resource(s)
Please list the resources as a list, for example:
- opc_instance
- OPC Network Config

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
JSON-

{
  "account" : "/Compute-*******/default",
  "description" : "RG-NAT",
  "tags" : [ ],
  "name" : "/Compute-*******/raj.x.xxx@xxx.com/RG-NAT",
  "objects" : [ {
    "account" : "/Compute-*******/default",
    "desired_state" : "inherit",
    "description" : "",
    "persistent" : true,
    "template" : {
      "managed" : true,
      "name" : "/Compute-*******/raj.x.xxx@xxx.com/RG-NAT_storage",
      "bootable" : true,
      "shared" : false,
      "imagelist" : "/oracle/public/OL_6.4_UEKR3_x86_64",
      "properties" : [ "/oracle/public/storage/default" ],
      "size" : "12G"
    },
    "label" : "RG-NAT_storage_1",
    "orchestration" : "/Compute-*******/raj.x.xxx@xxx.com/RG-NAT",
    "type" : "StorageVolume",
    "name" : "/Compute-*******/raj.x.xxx@xxx.com/RG-NAT/RG-NAT_storage"
  }, {
    "account" : "/Compute-*******/default",
    "desired_state" : "inherit",
    "description" : "RG-NAT",
    "persistent" : true,
    "template" : {
      "networking" : {
        "eth1" : {
          "vnic" : "/Compute-*******/raj.x.xxx@xxx.com/RG-NAT_eth1",
          "ip" : "10.0.0.20",
          "ipnetwork" : "/Compute-*******/raj.x.xxx@xxx.com/Gateway_OEL6IPN",
          "nat" : [ ],
          "vnicsets" : [ "/Compute-*******/raj.x.xxx@xxx.com/RG-NAT" ]
        },
        "eth0" : {
          "seclists" : [ "/Compute-*******/raj.x.xxx@xxx.com/dnsntpseclist" ],
          "nat" : "ipreservation:/Compute-*******/xxx@xxx.com/DNS_NTP_TEST","/Compute-*******/raj.x.xxx@xxx.com/NAT-IP-TEST",
          "dns" : [ "RG-NAT" ]
        }
      },
      "name" : "/Compute-*******/raj.x.xxx@xxx.com/RG-NAT",
      "storage_attachments" : [ {
        "volume" : "{{RG-NAT_storage_1:name}}",
        "index" : 1
      } ],
      "boot_order" : [ 1 ],
      "hostname" : "RG-NAT",
      "label" : "RG-NAT",
      "shape" : "oc3",
      "imagelist" : "/oracle/public/OL_6.4_UEKR3_x86_64",
      "sshkeys" : [ "/Compute-*******/xxx@xxx.com/DR_SSH" ]
    },
    "label" : "RG-NAT_instance",
    "orchestration" : "/Compute-*******/raj.x.xxx@xxx.com/RG-NAT",
    "type" : "Instance",
    "name" : "/Compute-*******/raj.x.xxx@xxx.com/RG-NAT/instance"
  } ],
  "desired_state" : "active"
}

### Debug Output
Error while uploading

### Panic Output
NA

### Expected Behavior
What should have happened?

### Actual Behavior
Error while uploading

**Comment by gupraj** [comment]
This is causing issue-

"nat" : "ipreservation:/Compute-/xxx@xxx.com/DNS_NTP_TEST","/Compute-/raj.x.xxx@xxx.com/NAT-IP-TEST"

**Comment by scross01** [comment]
@gupraj a couple of things: 

1. the `nat` attribute should defined as a list []:

```
"nat" : [ "ipreservation:/Compute-/xxx@xxx.com/DNS_NTP_TEST","ipreservation:/Compute-/raj.x.xxx@xxx.com/NAT-IP-TEST" ]
```

2. multiple IP reservations can only be provided for *IP Network interfaces*.  `eth0` is appears to be defined as a *Shared Network interface*. Only one IP Reservation is supported on a *Shared Network interface* according to the [creating instances  documentation](https://docs.oracle.com/en/cloud/iaas/compute-iaas-cloud/stcsg/creating-instances-using-launch-plans.html)

**Comment by gupraj** [comment]
@scross01  Thank you for help. Issue resolved.
