### ISSUE TITLE
OPC Error: Error running plan: 1 error(s) occurred:  * provider.opc: 401: {"message": "Incorrect username

### ISSUE THREAD

**Issue by rg193860** [terraform-providers/terraform-provider-opc#89]
Hi team,
I am trying to connect Oracle compute classic instance using OPC and Terraform.
Version terraform_0.10.8
OPC : 0.1.3.x

Error: Error running plan: 1 error(s) occurred:  * provider.opc: 401: {"message": "Incorrect username

But with same logins I am able to login to Oracle compute classic console and able to create instances.

* provider.opc: 401: {"message": "Incorrect username or password"}

Please check on this.
Thanks
Ravi
-----------------------------
code:
provider "opc" {
  identity_domain = "rg193860"
  endpoint        = "https://compute.gbcom-south-1.oraclecloud.com/"
  user            = "******@******"
  password        = "****"
}
 

resource "opc_compute_ip_reservation" "production" {
  parent_pool = "/oracle/public/ippool"
  permanent = true
### Debug Output
https://gist.github.com/rg193860/33cb0222ced52e068647dfca81746717
.

### Terraform Version
D:\terraform_0.10.8_windows_amd64>terraform -v
2017/11/09 16:36:06 [INFO] Terraform version: 0.10.8  44110772d9ffd0ec3589943c6
4c93c24a5fff06
2017/11/09 16:36:06 [INFO] Go runtime version: go1.9
2017/11/09 16:36:06 [INFO] CLI args: []string{"D:\\terraform_0.10.8_windows_amd
4\\terraform.exe", "-v"}
2017/11/09 16:36:06 [DEBUG] Attempting to open CLI config file: C:\Users\rgudur
\AppData\Roaming\terraform.rc
2017/11/09 16:36:06 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2017/11/09 16:36:06 [DEBUG] CLI config is &main.Config{Providers:map[string]str
ng{}, Provisioners:map[string]string{}, DisableCheckpoint:false, DisableCheckpo
ntSignature:false, PluginCacheDir:"", Credentials:map[string]map[string]interfa
e {}(nil), CredentialsHelpers:map[string]*main.ConfigCredentialsHelper(nil)}
2017/11/09 16:36:06 [INFO] CLI command args: []string{"version", "-v"}
2017/11/09 16:36:06 [DEBUG] plugin: waiting for all plugin processes to complet
...
Terraform v0.10.8

### Affected Resource(s)
OPC provider. for Oracle cloud compute classic.

### Debug Output
https://gist.github.com/rg193860/33cb0222ced52e068647dfca81746717

**Comment by scross01** [comment]
@rg193860 are you able to connect using the [opc cli](http://www.oracle.com/technetwork/topics/cloud/downloads/opc-cli-3096036.html) with the same credentials?  

Also check that you have the correct API REST Endpoint URL - this is shown in the Service Overview of the MyServices Dashboard, or select the Site dropdown at the top of the Service Console

**Comment by rg193860** [comment]
Thanks for comment Stephen. After much trail and error, raised Oracle support ticket. They took 3 days to fix. 
Issue is with welcome email after signup is not that much clear.  Welcome email says domain name is rg193860. 
Support says "Your compute namespace is /Compute-5873xxxxx , so the domain that needs to used most likely used with terrform is 5873xxxxx"
So now able to connect Oracle CLoud compute classic using above name space.

**Comment by scross01** [comment]
@rg193860 use the `5873xxxxx` Service Instance ID for the account as for the `identity_domain` value.

**Comment by scross01** [comment]
Documentation was undated to indicate to use Identity Service ID for IDCS accounts, and Identity Domain Name for Traditional Accounts.
