### ISSUE TITLE
How to use json,with terraform script.

### ISSUE THREAD

**Issue by gupraj** [terraform-providers/terraform-provider-opc#93]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.10.4.

### Affected Resource(s)
Please list the resources as a list, for example:
- opc_instance
- opc_storage_volume
- Terraform

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
Need details for instance creation,network configuration using JSON and terraform.

### Actual Behavior
N/A

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. JSON script to create instance,storage
2. terraform script to create full configuration, Instance/storage-using json template and network configuration.
3. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? For example: Running in EC2 Classic? Custom version of OpenStack? Tight ACLs?

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by scross01** [comment]
@gupraj can you provide more details for the question - are you trying to include JSON content as a value to the attribute?  You can embed multiline strings for JSON, or other formats, using "here doc" notation e.g.

```tf
data "template_file" "cloud-init-userdata-script" {
  template = <<JSON
{
  "userdata": "#!/bin/bash\necho 'Created by Terraform' > /etc/motd" 
}
JSON
}
```

Or are you trying to create the terraform configuration files in JSON format?
 (see https://www.terraform.io/docs/configuration/syntax.html#json-syntax)

**Comment by gupraj** [comment]
@scross01 Thanks for reply.
I wanted to create OPC instance using json template, as we want orchestration for our instance. so i wanted to write terraform code which will use my customized json as userdata to create then instance.

Below are the approach-

1- I will create network/security rule and others required object before creating instance using terraform.
2- I will use my customized json for instance creation and call them from terraform to create instance.


Note- As terraform does not support orchestration model, i need to use this approach.

Please suggest if we have option to create instance and other objects, from terraform with orchestration .

Thanks.

**Comment by gupraj** [comment]
Test Template for your reference :

{
  "account" : "/Compute-a494***/default",
  "description" : "TEMPLATE",
  "tags" : [ ],
  "name" : "/Compute-a494***/raj.a.gupta@xxx.com/TEMPLATE",
  "objects" : [ {
    "account" : "/Compute-a494***/default",
    "desired_state" : "inherit",
    "description" : "TEMPLATE",
    "persistent" : false,
    "template" : {
      "networking" : {
        "eth2" : {
          "vnic" : "/Compute-a494***/raj.a.gupta@xxx.com/TEMPLATE_eth2",
          "nat" : [ ],
          "ip" : "10.50.YY.Y",
          "vnicsets" : [ "/Compute-a494***/raj.a.gupta@xxx.com/TEMPLATE-VNICSET" ],
          "ipnetwork" : "/Compute-a494***/vihan.khare@xxx.com/PROD-DB-IPN2",
          "dns" : [ "TEMPLATE.xyz-erp.net" ]
        },
        "eth1" : {
          "vnic" : "/Compute-a494***/raj.a.gupta@xxx.com/TEMPLATE_eth1",
          "is_default_gateway" : true,
          "dns" : [ "TEMPLATE.xyz-erp.net" ],
          "ip" : "10.50.XX.X",
          "vnicsets" : [ "/Compute-a494***/raj.a.gupta@xxx.com/TEMPLATE-VNICSET" ],
          "ipnetwork" : "/Compute-a494***/raj.a.gupta@xxx.com/PROD-DB-IPN",
          "nat" : [ ]
        }
      },
      "name" : "/Compute-a494***/raj.a.gupta@xxx.com/TEMPLATE",
      "boot_order" : [ 1 ],
      "storage_attachments" : [ {
        "volume" : "{{TEMPLATE_storage_1:name}}",
        "index" : 1
      } ],
      "label" : "TEMPLATE",
      "shape" : "oc3",
      "imagelist" : "/oracle/public/OL_6.4_UEKR3_x86_64",
      "sshkeys" : [ "/Compute-a494***/ajay.h.sharma@xxx.com/infraprod" ]
    },
    "label" : "TEMPLATE_instance",
    "orchestration" : "/Compute-a494***/raj.a.gupta@xxx.com/TEMPLATE",
    "type" : "Instance",
    "name" : "/Compute-a494***/raj.a.gupta@xxx.com/TEMPLATE/instance"
  }, {
    "account" : "/Compute-a494***/default",
    "desired_state" : "inherit",
    "description" : "",
    "persistent" : true,
    "template" : {
      "managed" : true,
      "name" : "/Compute-a494***/raj.a.gupta@xxx.com/TEMPLATE_storage",
      "bootable" : true,
      "shared" : false,
      "imagelist" : "/oracle/public/OL_6.4_UEKR3_x86_64",
      "properties" : [ "/oracle/public/storage/default" ],
      "size" : "12G"
    },
    "label" : "TEMPLATE_storage_1",
    "orchestration" : "/Compute-a494***/raj.a.gupta@xxx.com/TEMPLATE",
    "type" : "StorageVolume",
    "name" : "/Compute-a494***/raj.a.gupta@xxx.com/TEMPLATE/TEMPLATE_storage"
  } ],
  "desired_state" : "active"
}

**Comment by gupraj** [comment]
data "template_file" "cloud-init-userdata-script" {
  template = <<JSON
{
  "userdata": "#!/bin/bash\necho 'Created by Terraform' > /etc/motd" 
}
JSON
}


Here how we can our test.json ? Please suggest

Thanjs

**Comment by scross01** [comment]
What is you reason for wanting to create the instances with an orchestration template rather than native terraform configuration?  

The `opc` provider doesn't currently support creation of orchestrations resources (see #14).  The `userdata` example above is for passing the the `opc-init` or `cloud-init` configuration to an instance, but you don't appear to need that based on your example. Some work is underway to look at enhancing specifically just the compute instance resource to support creation of an associated  orchestration template (v2), however 

When you say: 

> 1- I will create network/security rule and others required object before creating instance using terraform.

Are you creating them manually, or as part of a different terraform configuration?

If you are just trying to use the above test.json to create the instances, and you don't have any other dependent terraform configuration they you may be better off just using the `opc-cli` tool to create the orchestration, as you are not going to get any advantages of using terraform to manage the configuration lifecycle.

**Comment by gupraj** [comment]
Thanks @scross01 

1- Customer need orchestration for all the cloud instance, so I dont have choice to create instance from terarform, but i like to create from terraform only :-)

2- I am creating network/sec rule etc using terraform only.

Please suggest if we have anything in terraform to create instance but with orchestration.


Thanks

**Comment by kdvlr** [comment]
@scross01 - We need the ability to create orchestrations as well. 

My customer has seen the VMs crash multiple times now (with error Host Terminated). With the 
orchestration, it supports the ability to bring up another instance. However, with the launch plans, if the instances crashes, we have to detach the storage and attach it to a new instance.

**Comment by scross01** [comment]
@gupraj @kdvlr work is underway to look at adding orchestration support specifically just for instance creation - which should address you use cases. The proposal is that the instance would still be defined as a native Terraform resource, Terraform will take care of creating the orchestration for just the instance, all other resources, such as the storage etc, would remain outside of the orchestration (under direct Terraform control).

The advantage of having an 'orchestrated instance' is specifically for the HA scenario, so the orchestration actively monitors the instance state and will automatically restart a failed instance.
  
A side affect to be aware of when laying "Terraform -> Orchestration -> Instance" is Terraform loses the direct control over instance resource state, as the actual resource management has been delegated to the orchestration.  If the orchestration recreates a failed instance after the initial `terraform apply` the instance ID changes, so the Terraform state would be out of sync with the provisioned instance until the state is refreshed.

@mbfrahry fyi

**Comment by gupraj** [comment]
@scross01 @mbfrahry  Hope you are doing good.
Any news of orchestration work? 

Regards,

**Comment by scross01** [comment]
v1.0.1 adds initial support the creating instances with orchestrations

See this overview for more details.
https://medium.com/oracledevs/terraform-and-oracle-cloud-infrastructure-classic-orchestrations-e0fd39580f1e
